Xabaril/AspNetCore.Diagnostics.HealthChecks

README.md

When setting up HealthChecks I had trouble discovering what Nuget package to add for the UI. This documentation update should help with onboarding new users

Add clarity on how to include the UI package

---

build/dependencies.props
src/HealthChecks.Kafka/DependencyInjection/KafkaHealthCheckBuilderExtensions.cs
src/HealthChecks.Kafka/KafkaHealthCheck.cs

Adding support for compacted topics.

Added key to the kafka messages. Fix for #57

---

AspNetCore.Diagnostics.HealthChecks.sln
README.md
build.ps1
docker-compose.yml
src/HealthChecks.Consul/ConsulHealthCheck.cs
src/HealthChecks.Consul/DependencyInjection/ConsulHealthCheckBuilderExtensions.cs
src/HealthChecks.Consul/HealthChecks.Consul.csproj
test/FunctionalTests/FunctionalTests.csproj
test/FunctionalTests/HealthChecks.Consul/ConsulHealthCheckTests.cs
test/UnitTests/DependencyInjection/Consul/ConsulUnitTests.cs
test/UnitTests/UnitTests.csproj

I created an implementation for Consul, with Unit Tests and Functional Tests

Consul implementation

---

AspNetCore.Diagnostics.HealthChecks.sln
README.md
build.ps1
build/dependencies.props
src/HealthChecks.Hangfire/DependencyInjection/HangfireHealthCheckBuilderExtensions.cs
src/HealthChecks.Hangfire/HangfireHealthCheck.cs
src/HealthChecks.Hangfire/HangfireOptions.cs
src/HealthChecks.Hangfire/HealthChecks.Hangfire.csproj
src/HealthChecks.UI/package-lock.json
test/UnitTests/DependencyInjection/Hangfire/HangfireUnitTests.cs
test/UnitTests/UnitTests.csproj

Checking how many failed jobs the Hangfire instance currently has.

Added health check for Hangfire

---

src/HealthChecks.EventStore/DependencyInjection/EventStoreHealthCheckBuilderExtensions.cs
src/HealthChecks.RabbitMQ/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs
src/HealthChecks.RavenDB/DependencyInjection/RavenDBHealthCheckBuilderExtensions.cs

A minor fix to fix 3 static class name

Fixed 3 static class name.

---

README.md
build/dependencies.props
src/HealthChecks.UI/ServiceCollectionExtensions.cs

Added support for the expansion of environment variables in HealthCheckDatabaseConnectionString.
See #95 
@unaizorrilla

 Added support for the expansion of environment variables in HealthCheckDatabaseConnectionString.

---

samples/HealthChecks.UI.Sample/appsettings.json
src/HealthChecks.UI/Core/Notifications/WebHookFailureNotifier.cs
src/HealthChecks.UI/HealthChecks.UI.csproj
src/HealthChecks.UI/Keys.cs

[issue](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/111)

added descriptions in webhook

---

src/HealthChecks.Redis/RedisHealthCheck.cs

Issue #157: Reuse existing connection for ping on service startup

---

build/docker-images/HealthChecks.UI.Image/Dockerfile
docker-compose.yml

Switching per Microsoft [recommendation](https://devblogs.microsoft.com/dotnet/net-core-container-images-now-published-to-microsoft-container-registry/).

Switch to Microsoft container registry

---

src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs

This is similar to the recent fix for Issue [172](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/172).

Prevent CosmosDbHealthCheck form instantiating a new CosmosClient per call

---

src/HealthChecks.EventStore/EventStoreHealthCheck.cs

#189 fix unclosed connection in healthcheck

---

src/HealthChecks.MongoDb/MongoDbHealthCheck.cs

This PR fixes concurrency issue.
Also in general it's preferable to use standard methods that were properly tested than trying to repeat them for no reason
Can I ask you to merge it asap because this is a real issue in production and I had to go back to old version of the package that doesn't have the bug

Fix concurrency bug when two requests are sent at the same time

---

build/dependencies.props
src/HealthChecks.Elasticsearch/ElasticsearchHealthCheck.cs

This PR fix the issue #235 because currently Elasticsearch HealthCheck use NEST 6.1.0 and the lastest version is 7.1.0.
Regards!

Upgrade NEST version to 7.1.0

---

src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusTopicHealthCheck.cs
src/HealthChecks.AzureServiceBus/DependencyInjection/AzureServiceBusHealthCheckBuilderExtensions.cs

Fixes #248 
Update AzureServiceBusQueue and  FzureServiceBusTopic

Add a message configuration selector

---

build/dependencies.props
src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs

This PR updates the Microsoft.Azure.Cosmos dependency from 3.0.0.9-preview to the 3.1.1 version.
Regards!

Upgrade cosmos db version to 3.1.1

---

src/HealthChecks.EventStore/EventStoreHealthCheck.cs

The eventstore client method ```await connection.ConnectAsync()``` already completes 
after the init of the TcpConnection instance. It is then in the internal State "Connecting" 
and it is not indicating a success or failure.
To check the real result of the connection,
an event handler to the event Connected, Closed and ErrorOccurred
is required. 
Taken from the UnitTest of Eventstore:
https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core.Tests/ClientAPI/connect.cs 
Maybe it will fix related issue
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/273

EventStore does not check the connection itself

---

Nuget.config
src/HealthChecks.System/DependencyInjection/SystemHealthCheckBuilderExtensions.cs
src/HealthChecks.System/ProcessHealthCheck.cs
src/HealthChecks.System/WindowsServiceHealthCheck.cs
src/HealthChecks.UI/package-lock.json
test/FunctionalTests/HealthChecks.System/WindowsServiceHealthcheckTests.cs
test/UnitTests/DependencyInjection/System/ProcessHealthCheckUnitTests.cs
test/UnitTests/UnitTests.csproj

Process and windows service healthchecks

Process and windows service healthchecks

---

src/HealthChecks.UI/Core/Notifications/WebHookFailureNotifier.cs

Related to https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/321
@unaizorrilla  @lurumad

.equals with ignorecase compare is not working with sqlite and linq

---

README.md

Fix: #341 minor spelling mistake in README.md

---

src/HealthChecks.AzureStorage/AzureBlobStorageHealthCheck.cs
src/HealthChecks.AzureStorage/AzureQueueStorageHealthCheck.cs
src/HealthChecks.AzureStorage/AzureTableStorageHealthCheck.cs
src/HealthChecks.AzureStorage/DependencyInjection/AzureStorageHealthCheckBuilderExtensions.cs
src/HealthChecks.UI/package-lock.json
test/UnitTests/DependencyInjection/AzureStorage/AzureBlobStorageUnitTests.cs
test/UnitTests/DependencyInjection/AzureStorage/AzureQueueStorageUnitTests.cs
test/UnitTests/DependencyInjection/AzureStorage/AzureTableStorageUnitTests.cs

Includes check if existing for Container, Table and Queue in Azure Storage
#309

Azure Storage, exists Container, Table and Queue 

---

README.md

fix Azure IotHub package name in readme.md

---

build/dependencies.props

Upgrade confluente.kafka package to 1.3.0
#371

[2.2] Kafka healthcheck upgrade to 1.3.0 #371

---

src/HealthChecks.UI/Core/Discovery/K8S/Extensions/IKubernetesExtensions.cs
src/HealthChecks.UI/Core/Discovery/K8S/KubernetesDiscoveryOptions.cs

Please reference the issue this PR will close: #449 

Fix #449 - Configured k8s discovery namespaces are ignored

---

build/dependencies.props
src/HealthChecks.Kafka/DependencyInjection/KafkaHealthCheckBuilderExtensions.cs
src/HealthChecks.Kafka/KafkaHealthCheck.cs

I would like to be able to set what topic the health check is producing messages to.

Be able to make kafka healthcheck topic configurable

---

src/HealthChecks.UI/ServiceCollectionExtensions.cs
src/HealthChecks.UI/package-lock.json

This is a little step in the right direction in terms of #351. It is not a breaking change, and it still doesn't fully resolve the issue, but it reduces the `BuildServiceProvider` calls by one at least.
I will make an additional PR later for the rest.

Non-breaking changes towards fixing issue #351

---

README.md

The link to the tutorials section was broken in the Readme file.
Fix for issue #497 

Fixed the anchor link to the tutorials section in the Readme.README.md

---

build/dependencies.props
src/HealthChecks.UI/Core/HostedService/UIInitializationHostedService.cs
test/FunctionalTests/HealthChecks.UI/DatabaseProviders/UpdateConfigurationTests.cs

Right now, the preview version of the new UI with storage provider packages only allows adding new services but not updating uris of existing healthcheck configuration names
**Which issue(s) this PR fixes**:  #513

UI Hosted Service - Update existing configuration Uris

---

README.md

**What this PR does / why we need it**: update readme.md file only
**Which issue(s) this PR fixes**: #514: Add missed data about packages/resources to README.md file
Please reference the issue this PR will close: #514
**Special notes for your reviewer**: --
**Does this PR introduce a user-facing change?**: only to documentation

Add missed data to readme.md file.

---

build/dependencies.props
src/HealthChecks.RabbitMQ/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs
src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs

Add support for ConnectionFactory on Rabbitmq registration

Working again on connection factory support and reuse connections

---

build/dependencies.props
src/HealthChecks.System/DependencyInjection/SystemHealthCheckBuilderExtensions.cs
src/HealthChecks.System/WindowsServiceHealthCheck.cs

**Which issue(s) this PR fixes**: #541 

[Windows Service hc] Allow ServiceController machinename

---

src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusSubscriptionHealthCheck.cs
src/HealthChecks.AzureServiceBus/DependencyInjection/AzureServiceBusHealthCheckBuilderExtensions.cs
test/UnitTests/DependencyInjection/AzureServiceBus/AzureServiceBusSubscriptionUnitTests.cs

**What this PR does / why we need it**: To add Azure Service Bus Subscription healthcheck, which is currenlty a missing feature.
**Which issue(s) this PR fixes**: This will add a missing feature of healthchecking an Azure ServiceBus Subscription
Please reference the issue this PR will close: #604 
**Special notes for your reviewer**: N/A

Azure ServiceBus Subscription HealthCheck

---

doc/ui-docker.md

Corrected typo in docker readme

Corrected typo

---

AspNetCore.Diagnostics.HealthChecks.sln
README.md
samples/HealthChecks.UI.Oidc/HealthChecks.UI.Oidc.csproj
samples/HealthChecks.UI.Oidc/Program.cs
samples/HealthChecks.UI.Oidc/Startup.cs
samples/HealthChecks.UI.Oidc/appsettings.Development.json
samples/HealthChecks.UI.Oidc/appsettings.json

Add an example for how to restrict access for users on HealthChecks UI using an OpenId Connect server.
Role Based Healthcheck API #646

Restrict access UI with OIDC

---

src/HealthChecks.MongoDb/MongoDbHealthCheck.cs

This PR fix the memory leak in the case of a MongoDb cluster with the `w=majority` flag
#655
Please reference the issue this PR will close: #655

Changed the collection type to fix #655

---

build/dependencies.props

Fixes #710
See also https://github.com/dotnet/SqlClient/issues/825

Upgrade Microsoft.Data.SqlClient to 2.1.1

---

build/dependencies.props
src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs
src/HealthChecks.CosmosDb/HealthChecks.CosmosDb.csproj

This PR is to fix the issue described in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/719
#719 
No

Changed dependency from Azure.Cosmos to Microsoft.Azure.Cosmos

---

README.md

It fixes the documentation
#775

Fix nuget name in documentation

---

build/dependencies.props

**What this PR does / why we need it**:  release version of KeyVault package is better than prerelease

Use release version of KeyVault package

---

README.md
build/dependencies.props
src/HealthChecks.AzureStorage/AzureFileShareHealthCheck.cs
src/HealthChecks.AzureStorage/DependencyInjection/AzureStorageHealthCheckBuilderExtensions.cs
src/HealthChecks.AzureStorage/HealthChecks.AzureStorage.csproj

This pull request adds a health check for Azure file shares using the "exists" action from the SDK.
None.
**Does this PR introduce a user-facing change?**: 
No.

Azure File Share Healthcheck

---

src/HealthChecks.Network/SmtpHealthCheck.cs

Not a big change - just a missing space.

Fix: Missing space in healt check result.

---

src/HealthChecks.Aws.S3/README.md
src/HealthChecks.Azure.IoTHub/README.md
src/HealthChecks.AzureKeyVault/README.md
src/HealthChecks.IbmMQ/README.md
src/HealthChecks.Rabbitmq/README.md

Fix cs moniker

---

README.md
src/HealthChecks.Publisher.Prometheus/DependencyInjection/PrometheusGatewayHealthCheckBuilderExtensions.cs

Badges, formatting/ordering, whitespaces.

Edit README

---

Directory.Build.targets

See https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy/issues/28

Bump EventStore.Client version

---

Directory.Build.props
src/HealthChecks.AzureServiceBus/DependencyInjection/AzureServiceBusHealthCheckBuilderExtensions.cs
src/HealthChecks.AzureStorage/DependencyInjection/AzureStorageHealthCheckBuilderExtensions.cs
src/HealthChecks.Consul/DependencyInjection/ConsulHealthCheckBuilderExtensions.cs
src/HealthChecks.MongoDb/DependencyInjection/MongoDbHealthCheckBuilderExtensions.cs
src/HealthChecks.NpgSql/DependencyInjection/NpgSqlHealthCheckBuilderExtensions.cs
src/HealthChecks.Rabbitmq/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs
src/HealthChecks.Redis/DependencyInjection/RedisHealthCheckBuilderExtensions.cs
src/HealthChecks.Solr/DependencyInjection/SolrHealthCheckBuilderExtensions.cs
src/HealthChecks.System/DependencyInjection/SystemHealthCheckBuilderExtensions.cs

SourceLink was completely broken.

Fix broken SourceLink

---

src/HealthChecks.Oracle/HealthChecks.Oracle.csproj

Multitarget Oracle health check

---

src/HealthChecks.Gcp.CloudFirestore/HealthChecks.Gcp.CloudFirestore.csproj

Bump Google.Cloud.Firestore

---

src/HealthChecks.AzureKeyVault/AzureKeyVaultOptions.cs
src/HealthChecks.AzureKeyVault/DependencyInjection/AzureKeyVaultHealthChecksBuilderExtensions.cs

Fix AzureKeyVaultHealthChecksBuilderExtensions

---

src/HealthChecks.SqlServer/HealthChecks.SqlServer.csproj
src/HealthChecks.SqlServer/SqlServerHealthCheck.cs
test/HealthChecks.SqlServer.Tests/Functional/SqlServerHealthCheckTests.cs

replaces and fixes #1376 
https://github.com/dotnet/SqlClient/issues/1479
https://github.com/dotnet/SqlClient/blob/main/release-notes/4.0/4.0.0.md#breaking-changes

Bump Microsoft.Data.SqlClient from 3.0.1 to 5.0.0

---

src/HealthChecks.ArangoDb/ArangoDbHealthCheck.cs
src/HealthChecks.ArangoDb/ArangoDbOptions.cs
src/HealthChecks.ArangoDb/DependencyInjection/ArangoDbHealthCheckBuilderExtensions.cs
src/HealthChecks.AzureDigitalTwin/AzureDigitalTwinHealthCheck.cs
src/HealthChecks.AzureDigitalTwin/AzureDigitalTwinInstanceHealthCheck.cs
src/HealthChecks.AzureDigitalTwin/AzureDigitalTwinModelsHealthCheck.cs
src/HealthChecks.AzureDigitalTwin/AzureDigitalTwinSubscriptionHealthCheck.cs
src/HealthChecks.Gremlin/DependencyInjection/GremlinHealthCheckBuilderExtensions.cs
src/HealthChecks.Gremlin/GremlinHealthCheck.cs
src/HealthChecks.Gremlin/GremlinOptions.cs
src/HealthChecks.IbmMQ/DependencyInjection/IbmMQHealthCheckBuilderExtensions.cs
src/HealthChecks.IbmMQ/IbmMQHealthCheck.cs
src/HealthChecks.Nats/DependencyInjection/NatsHealthCheckBuilderExtensions.cs
src/HealthChecks.Nats/NatsHealthCheck.cs
src/HealthChecks.Nats/NatsOptions.cs
src/HealthChecks.SendGrid/DependencyInjection/SendGridHealthCheckExtensions.cs
src/HealthChecks.SendGrid/SendGridHealthCheck.cs

Convert some projects to file-scoped namespaces

---

src/HealthChecks.Kafka/DependencyInjection/KafkaHealthCheckBuilderExtensions.cs
src/HealthChecks.Kafka/KafkaHealthCheck.cs
test/HealthChecks.Kafka.Tests/HealthChecks.Kafka.approved.txt
test/UnitTests/DependencyInjection/S3/S3UnitTests.cs

Fix memory leak in KafkaHealthCheck

---

src/HealthChecks.Publisher.CloudWatch/DependencyInjection/CloudWatchHealthCheckBuilderExtensions.cs

fix: miswriting

---

src/HealthChecks.AzureKeyVault/HealthChecks.AzureKeyVault.csproj

Remove unused dependencies from the HealthChecks.AzureKeyVault project.
Please reference the issue this PR will close: #1497
This also solves #1363 because that package isn't used._
No

Remove unused dependencies from HealthChecks.AzureKeyVault

---

src/HealthChecks.ApplicationStatus/README.md

Changed a leftover copied from another readme file.
- Documentation change, no runtime changes.
No.

Fixed a copy error

---

src/HealthChecks.AzureServiceBus/AzureServiceBusHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusSubscriptionHealthCheck.cs
test/HealthChecks.AzureServiceBus.Tests/HealthChecks.AzureServiceBus.approved.txt

Moves QueueHealth and SubscriptionHealth to using PeekMessagesAsync
Please reference the issue this PR will close: #1503

Moving QueueHealth and SubscriptionHealth to use PeekMessagesAsync

---

test/HealthChecks.Nats.Tests/Functional/NatsHealthCheckTests.cs

Helps to track https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/actions/runs/3345853596/jobs/5541911646

More info for Nats tests

---

.github/workflows/healthchecks_applicationstatus_cd.yml
.github/workflows/healthchecks_applicationstatus_cd_preview.yml
.github/workflows/healthchecks_arangodb_cd.yml
.github/workflows/healthchecks_arangodb_cd_preview.yml
.github/workflows/healthchecks_aws_s3_cd.yml
.github/workflows/healthchecks_aws_secretsmanager_cd.yml
.github/workflows/healthchecks_aws_sns_cd.yml
.github/workflows/healthchecks_aws_sqs_cd.yml
.github/workflows/healthchecks_aws_systemsmanager_cd.yml
.github/workflows/healthchecks_azure_digitaltwin_cd.yml
.github/workflows/healthchecks_azure_iothub_cd .yml
.github/workflows/healthchecks_azurestorage_cd.yml
.github/workflows/healthchecks_consul_cd.yml
.github/workflows/healthchecks_consul_cd_preview.yml
.github/workflows/healthchecks_cosmosdb_cd.yml
.github/workflows/healthchecks_cosmosdb_cd_preview.yml
.github/workflows/healthchecks_documentdb_cd.yml
.github/workflows/healthchecks_documentdb_cd_preview.yml
.github/workflows/healthchecks_dynamodb_cd.yml
.github/workflows/healthchecks_dynamodb_cd_preview.yml
.github/workflows/healthchecks_elasticsearch_cd.yml
.github/workflows/healthchecks_elasticsearch_cd_preview.yml
.github/workflows/healthchecks_gcp_cloudfirestore_cd.yml
.github/workflows/healthchecks_gcp_cloudfirestore_cd_preview.yml
.github/workflows/healthchecks_gremlin_cd.yml
.github/workflows/healthchecks_gremlin_cd_preview.yml
.github/workflows/healthchecks_hangfire_cd.yml
.github/workflows/healthchecks_hangfire_cd_preview.yml
Directory.Build.props
Directory.Build.targets

Add readme into nupkg

---

doc/styles-branding.md
src/HealthChecks.ArangoDb/ArangoDbOptions.cs
src/HealthChecks.UI/Configuration/Settings.cs

Try labeler

---

.github/labeler.yml
.github/workflows/healthchecks_kafka_cd.yml
.github/workflows/healthchecks_kafka_cd_preview.yml
.github/workflows/healthchecks_kafka_ci.yml
src/HealthChecks.Kafka/DependencyInjection/KafkaHealthCheckBuilderExtensions.cs
src/HealthChecks.Kafka/KafkaHealthCheck.cs
src/HealthChecks.Kafka/KafkaHealthCheckOptions.cs
test/HealthChecks.Kafka.Tests/HealthChecks.Kafka.approved.txt

Introduce KafkaHealthCheckOptions

---

src/HealthChecks.ApplicationStatus/DependencyInjection/ApplicationStatusHealthCheckBuilderExtensions.cs

Fix memory leak

---

src/HealthChecks.MongoDb/MongoDbHealthCheck.cs

Saves some allocations.
ping @ThumNet

Optimize MongoDbHealthCheck

---

src/HealthChecks.Prometheus.Metrics/LivenessPrometheusMetrics.cs
src/HealthChecks.Publisher.Prometheus/LivenessPrometheusMetrics.cs
test/HealthChecks.Prometheus.Metrics.Tests/HealthChecks.Prometheus.Metrics.approved.txt
test/HealthChecks.Publisher.Prometheus.Tests/HealthChecks.Publisher.Prometheus.approved.txt

Fix Non-Eng Encoding for browser.
Please reference the issue this PR will close: #1694
-
-

Prometheus - Wrong Encoding used by the browser

---

src/HealthChecks.IbmMQ/DependencyInjection/IbmMQHealthCheckBuilderExtensions.cs
src/HealthChecks.IbmMQ/HealthChecks.IbmMQ.csproj
src/HealthChecks.IbmMQ/IbmMQHealthCheck.cs

https://www.ibm.com/docs/en/ibm-mq/9.3?topic=net-installing-mq-classes

Bump IBMMQDotnetClient to 9.3.2 and deprecate netstandard2.0 TFM

---

src/CallerArgumentExpressionAttribute.cs
src/HealthChecks.Network/DnsResolveHealthCheck.cs
src/HealthChecks.Network/DnsResolveHostCountHealthCheck.cs
src/HealthChecks.Network/HealthChecks.Network.csproj
src/HealthChecks.Network/SslHealthCheck.cs
src/HealthChecks.Uris/HealthChecks.Uris.csproj

These projects contain ifdefs.

Add missed net5/net6 TFMs

---

src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs

allowIntegerValues: true

---

.github/workflows/healthchecks_consul_ci.yml

https://github.com/hashicorp/consul/issues/17973

Fix consul CI

---

.github/workflows/healthchecks_influxdb_ci.yml

Fix InfluxDB CI workflow #1868

---

.github/workflows/healthchecks_ui_ci.yml
AspNetCore.Diagnostics.HealthChecks.sln
src/HealthChecks.UI.Data/HealthChecksDb.cs
src/HealthChecks.UI.InMemory.Storage/HealthChecksUIBuilderExtensions.cs
src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/Extensions/ApplicationBuilderExtensions.cs
src/HealthChecks.UI/Extensions/EndpointRouteBuilderExtensions.cs
src/HealthChecks.UI/Middleware/UIApiEndpointMiddleware.cs
src/HealthChecks.UI/Middleware/UIApiRequestLimitingMidleware.cs
test/HealthChecks.UI.Data.Tests/HealthChecks.UI.Data.Tests.csproj
test/HealthChecks.UI.Data.Tests/HealthChecks.UI.Data.approved.txt
test/HealthChecks.UI.Data.Tests/HealthChecksDbTests.cs
test/HealthChecks.UI.Tests/Functional/UIApiRequestLimitingTests.cs

Fix ui_api_request_limiting tests

---

src/HealthChecks.OpenIdConnectServer/DependencyInjection/IdSvrHealthCheckBuilderExtensions.cs
src/HealthChecks.OpenIdConnectServer/IdSvrHealthCheck.cs
test/HealthChecks.OpenIdConnectServer.Tests/HealthChecks.OpenIdConnectServer.approved.txt

Expose Identity Server discover configuration segment

---

src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs

Handle not OK HTTP status codes in HealthCheckReportCollector

---

src/HealthChecks.SignalR/DependencyInjection/SignalRHealthCheckBuilderExtensions.cs
test/HealthChecks.SignalR.Tests/HealthChecks.SignalR.approved.txt

See #1943.
Thanks to @esskar for PR.

Provide overload with IServiceProvider to AddSignalRHub

---

build/versions.props
src/HealthChecks.UI/Middleware/UIApiEndpointMiddleware.cs

Adds camelCase serialization for UI API Endpoint.
**Which issue(s) this PR fixes**: #1971

Fix serialization for camelCase for UI Api Endpoint

---

src/HealthChecks.UI/Middleware/UIApiEndpointMiddleware.cs

Order health checks entries by name to have a consistent list when adding new health checks in microservices 
When adding a new health check in any new or existing microservices, would be good to have them order by name
- [x ] Code compiles correctly

Order health checks entries

---

.github/workflows/healthchecks_azurekeyvault_secrets_cd.yml
.github/workflows/healthchecks_azurekeyvault_secrets_cd_preview.yml
.github/workflows/healthchecks_azurekeyvault_secrets_ci.yml

This PR add missing pipelines for new Azure Key Vault Secrets package added recently

Added missing key vault secrets package pipelines

---

.github/dependabot.yml

**What this PR does / why we need it**:  Fixing a formatting issue introduced in [2018](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2018)
**Which issue(s) this PR fixes**:  [2018](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2018)
Please reference the issue this PR will close: #2018

Fixing the dependabot formatting

---

build/versions.props

Add missing version suffix to package [AspNetCore.HealthChecks.Azure.KeyVault.Secrets](https://www.nuget.org/packages/AspNetCore.HealthChecks.Azure.KeyVault.Secrets)

Added missing version suffix for new package azure key vaul secrets

---

build/versions.props

Fix mysql ui storage package as preview because pomelo is on preview also

Set preview version for mysql ui storage package

---

build/versions.props
src/HealthChecks.SqlServer/HealthChecks.SqlServer.csproj

This PR close #2182 
- [ x] Code compiles correctly
- [ x] Unit tests passing
- [ x] End-to-end tests passing

Update Microsoft.Data.SqlClient package reference

---

build/docker-images/HealthChecks.UI.Image/HealthChecks.UI.Image.csproj
src/HealthChecks.AzureDigitalTwin/HealthChecks.AzureDigitalTwin.csproj
test/HealthChecks.Azure.Data.Tables.Tests/HealthChecks.Azure.Data.Tables.Tests.csproj
test/HealthChecks.Azure.KeyVault.Secrets.Tests/HealthChecks.Azure.KeyVault.Secrets.Tests.csproj
test/HealthChecks.Azure.Messaging.EventHubs.Tests/HealthChecks.Azure.Messaging.EventHubs.Tests.csproj
test/HealthChecks.Azure.Storage.Blobs.Tests/HealthChecks.Azure.Storage.Blobs.Tests.csproj
test/HealthChecks.Azure.Storage.Files.Shares.Tests/HealthChecks.Azure.Storage.Files.Shares.Tests.csproj
test/HealthChecks.Azure.Storage.Queues.Tests/HealthChecks.Azure.Storage.Queues.Tests.csproj
test/HealthChecks.AzureDigitalTwin.Tests/HealthChecks.AzureDigitalTwin.Tests.csproj
test/HealthChecks.AzureKeyVault.Tests/HealthChecks.AzureKeyVault.Tests.csproj
test/HealthChecks.AzureServiceBus.Tests/HealthChecks.AzureServiceBus.Tests.csproj

* Bump Azure.Identity from 1.10.4 to 1.12.0
* Closes: #2173

fix:  Azure Identity CVE-2024-35255

---

README.md

I was reading the README and I came across a section that seemed like it was written by a non-native English speaker (lines 445-446), so I started fixing that. Then I proof-read the rest of the readme file to see what else there was.
No issue created.
Readme only.

README grammar/clarity fixes

---

src/HealthChecks.UI/HealthChecks.UI.csproj

Please reference the issue this PR will close: #2209

Update KubernetesClient Package Version to 14.0.2

---

.github/workflows/healthchecks_kafka_ci.yml
test/HealthChecks.Kafka.Tests/Functional/KafkaHealthCheckTests.cs

Please reference the issue this PR will close: #2280 

Fix Kafka broken ci

---

src/HealthChecks.Milvus/HealthChecks.Milvus.csproj

Disable milvus sign assembly

---

.github/workflows/healthchecks_eventstore_ci.yml
.github/workflows/healthchecks_eventstore_grpc_ci.yml

Use immutable tag for eventstore because lts failed to start

---

.github/labeler.yml
.github/workflows/label.yml
src/HealthChecks.Kafka/DependencyInjection/KafkaHealthCheckBuilderExtensions.cs

Labeler action stopped working after updating to v5 because it had breaking changes:
https://github.com/actions/labeler/blob/main/README.md#breaking-changes-in-v5
This PR will fix this issue.

Fix labeler breaking change after updating to v5

---

.github/labeler.yml

Fix labeler.yml

---

.github/workflows/healthchecks_redis_ci.yml

Reusable GH action for Redis ci

---

.github/workflows/healthchecks_mongodb_ci.yml
Directory.Packages.props
test/HealthChecks.MongoDb.Tests/Functional/MongoDbHealthCheckTests.cs
test/HealthChecks.MongoDb.Tests/HealthChecks.MongoDb.Tests.csproj
test/HealthChecks.MongoDb.Tests/MongoDbContainerFixture.cs

Migrate HealthChecks.MongoDb tests to Testcontainers

---

.github/workflows/healthchecks_rabbitmq_ci.yml
Directory.Packages.props
test/HealthChecks.RabbitMQ.Tests/Functional/RabbitHealthCheckTests.cs
test/HealthChecks.RabbitMQ.Tests/HealthChecks.RabbitMQ.Tests.csproj
test/HealthChecks.RabbitMQ.Tests/RabbitMQContainerFixture.cs
test/HealthChecks.RabbitMQ.v6.Tests/Functional/RabbitHealthCheckTests.cs
test/HealthChecks.RabbitMQ.v6.Tests/HealthChecks.RabbitMQ.v6.Tests.csproj

Migrate HealthChecks.Rabbitmq tests to Testcontainers

---

.github/workflows/healthchecks_milvus_ci.yml
Directory.Packages.props
test/HealthChecks.Milvus.Tests/Functional/MilvusHealthCheckTests.cs
test/HealthChecks.Milvus.Tests/HealthChecks.Milvus.Tests.csproj
test/HealthChecks.Milvus.Tests/MilvusContainerFixture.cs

Contributes to https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2335

Migrate HealthChecks.Milvus tests to Testcontainers

---

test/HealthChecks.Milvus.Tests/Functional/MilvusHealthCheckTests.cs
test/HealthChecks.Milvus.Tests/MilvusContainerFixture.cs

Update MilvusContainerFixture namespace

---

.github/workflows/healthchecks_kafka_ci.yml
Directory.Packages.props
docker-compose.yml
test/HealthChecks.Kafka.Tests/Functional/KafkaHealthCheckTests.cs
test/HealthChecks.Kafka.Tests/HealthChecks.Kafka.Tests.csproj
test/HealthChecks.Kafka.Tests/KafkaContainerFixture.cs

Migrate HealthChecks.Kafka tests to Testcontainers
