src/HealthChecks.AzureServiceBus/AzureEventHubHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusTopicHealthCheck.cs
src/HealthChecks.AzureServiceBus/HealthChecks.AzureServiceBus.csproj
test/UnitTests/DependencyInjection/AzureServiceBus/AzureEventHubUnitTests.cs

Tried to keep as close to the Redis implementation as I could for the Service Bus one as ServiceBusConnection is exposed which helps.
However, Event Hub does not expose this so I made the client initialise in the constructor instead.
I've also updated the libraries. The Service Bus update is necessary to expose the connection so needs to be at minimum 3.X.X.
If I need to move them down to a just the latest major I can do that.

Service Bus + Event Hub: Not a new connection for each check

---

build/dependencies.props
src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusTopicHealthCheck.cs

Noticed today whilst trying out the new fixes for the re-used QueueClient that if you use the same connection string but are checking against a different queue for health it will only ever check one as it is keyed off the connection string.
I've changed the code to key off both the connection string and the name of the queue.

[Azure Service Bus] Multiple Queue on same connection string bug fix

---

build/dependencies.props
src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusTopicHealthCheck.cs

Sorry about this, I just realised the code I committed before was pretty flawed! Was not actually using the new key for adding so it would work once then fail on every subsequent request.
Updated `dependencies.props` this time as well

[Azure Service Bus] Move out string to connection key as it was not being used for adding

---

build/dependencies.props
src/HealthChecks.RavenDB/HealthChecks.RavenDB.csproj

In previous PR #77 was add package `HealthChecks.RavenDB` with incorrect tag `MongoDB`.
I changed it into `RavenDB`.

Fixed incorrect package tag in RavenDB package

---

src/HealthChecks.Uris/UriHealthCheck.cs
src/HealthChecks.Uris/UriHealthCheckOptions.cs

* Add `Timeout` option to `UriHealthCheckOptions`
* Pass health-check `CancellationToken` during HTTP request within `UriHealthCheck`
Related to https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/81 and https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/60

Allow configurable timeout for URI health-checks

---

build/dependencies.props
src/HealthChecks.MongoDb/DependencyInjection/MongoDbHealthCheckBuilderExtensions.cs
src/HealthChecks.MongoDb/MongoDbHealthCheck.cs
test/UnitTests/DependencyInjection/MongoDb/MongoUnitTests.cs

Hi!
It will be good if clients are able to pass MogoClientSettings to healthcheck (for example with SSL settings).

Add MongoClientSettings support for MongoDbHealthCheck

---

build/dependencies.props
src/HealthChecks.RabbitMQ/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs
src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs

The rabbitMq health check was missing tls option, thus it would be useless in many cases where tls with rabbitMq is enabled.

extended rabbitMq health check with tls option.

---

src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/ServiceCollectionExtensions.cs

I wanted to be able to configure the healthchecks in an application where I install the UI nuget package.

ability to setup settings

---

build/dependencies.props
src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs

It created non-used and non-disposed objects for TelemetryConfiguration which can cause OutOfMemory exceptions. Cleaned the old code ensureing only one TelemetryConfiguration object is created for a singleton instance of TelemetryClient

Cleaned old code for ApplicationInsightsPublisher Issue #122

---

build/dependencies.props
samples/HealthChecks.UIAndApiCustomization/Startup.cs
src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollectorHostedService.cs
src/HealthChecks.UI/ServiceCollectionExtensions.cs

We received a PR some weeks ago to expose Action<Settings> so remote endpoints, webhooks and UI stuff can be configured by code instead of using appsettings.json.
This commit allows combining appsettings.json with Action<Settings> configuration callback or start configuring the checks from scratch without appsetting.json file.
However, it is not very friendly to apply configuration with the current settings class, and although we are not applying any kind of **validations** on settings yet, the current configuration class does not allow to do it as we expose collections and settings directly:
```csharp
settings.HealthChecks.Add(new HealthCheckSetting
{ 
Name = "api1", Uri = "http://localhost:5000/health-ui
});
settings.WebHooks.Add(new WebHookNotification
{
Name = "webhook1",
Uri = …
```

Add fluent api configuration for healthchecks

---

src/HealthChecks.RavenDB/DependencyInjection/RavenDBHealthCheckBuilderExtensions.cs
src/HealthChecks.RavenDB/RavenDBHealthCheck.cs
src/HealthChecks.RavenDB/RavenDBOptions.cs
test/FunctionalTests/HealthChecks.RavenDB/RavenDBWithOptionsHealthCheckTests.cs
test/FunctionalTests/HealthChecks.RavenDB/RavenDBWithSingleConnectionStringHealthCheckTests.cs
test/UnitTests/DependencyInjection/RavenDB/RavenWithOptionsUnitTests.cs
test/UnitTests/DependencyInjection/RavenDB/RavenWithSingleConnectionStringUnitTests.cs

With this pull request, I have added a method overload to allow user to pass <s>array of Raven URLs</s> `RavenDBOptions` instead of just single connection string. Note that existing method which allows the user to pass single connection string is still there but it has been marked `Obsolete`.
**Why this change?**
- This change is useful to test the health check for the Raven DB Cluster (that is multiple nodes) instead of a single connection string. For Load Balance and Fail over scenarios we would have multiple connection strings instead of one.
- In addition to this, `RavenDBOptions` also supports certificate authentication. That is user can _optionally_ pass the authentication certificate, which should ideally be a requirement for any production workload (like ours)
As an alternate …

Added overload to Raven Health check to allow user to pass RavenDBOptions

---

src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs
src/HealthChecks.Publisher.ApplicationInsights/DependencyInjection/ApplicationInsightsHealthCheckBuilderExtensions.cs

Fix for #138 that makes it possible to configure the Application Insights publisher to only publish reports that indicate an unhealthy state by adding an optional flag `excludeHealthyReports`. 
When the publisher is configured to publish the details (using `saveDetailedReport`) only those detailed reports indicating an unhealthy state will be published if `excludeHealthyReports` is set to `true`
I am all open for creating a functional test for this (as there are none for this particalur publisher) but I would like to add a dependency to [Moq](https://github.com/Moq/moq4/wiki/Quickstart) or [NSubstitute](https://nsubstitute.github.io/) in order to be able to fake the application insights classes involved. If that is ok with you I can add those tests, otherwise I need to figure out other …

exclude reports that indicate a healthy status

---

src/HealthChecks.Consul/ConsulHealthCheck.cs
src/HealthChecks.Consul/ConsulOptions.cs

I have read [Don't push your pull request](https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/). I'm sorry if my PR offends any maintainer. You guys are doing great work.
But hopefully this change is so minimal, that it will not affect the greater scheme of things in any unexpected way.

Add support for Basic Auth to ConsulHealthCheck

---

src/HealthChecks.AzureStorage/DependencyInjection/AzureStorageHealthCheckBuilderExtensions.cs
test/UnitTests/DependencyInjection/AzureStorage/AzureQueueStorageUnitTests.cs

In our project, we've faced an issue regarding the health checks of the storage queue within the package: **AspNetCore.HealthChecks.AzureStorage**
The problem was, that no matter what connection string has been passed to the health check, the result was always healthy.
After a quick look in the code, we found out, that the handling of the storage queue doesn't follow the same behavior as the tables and blobs.
For all three storage types, there is an option to pass user defined tags to the health check. However, the health check extension for the queue ignores them and uses an internal identifier.
The simple solution here is to align the behavior of the storage queue to the behavior of the table and blobs.
Instead of `new string[] { AZUREQUEUE_NAME }` which has been used as tags, no matter …

Add support for custom tags and failure status of azure storage queues

---

src/HealthChecks.Hangfire/HangfireHealthCheck.cs

Addressing issue #169.   Small fixes to some spelling / grammer issues in HangfireHealthCheck.

Fix spelling/grammer issues in HangfireHealthCheck error message.

---

docker-compose.yml

wnameless/oracle-xe-11g docker image no longer exists as Oracle DMCA'd it. See https://github.com/wnameless/docker-oracle-xe-11g/issues/118  
This PR changes it to be built from source instead.  
Note that if you already have the wnameless/oracle-xe-11g docker image cached locally, it will still be working for you, so delete that image to reproduce the issue.

Fix functional tests running locally

---

src/HealthChecks.UI/Core/Data/Configuration/HealthCheckExecutionHistoryMap.cs
src/HealthChecks.UI/Core/Data/Configuration/HealthCheckFailureNotificationsMap.cs

hi, thx for providing healthchecks code.
We have an error, only in our Docker/Rancher environment as this: 'Unknown Date' with no exception or details. This is not true json, witch have the side effect, that all logning is disgarded.
`
21.5.2019 14.03.13{"Timestamp":"2019-05-21T12:03:13.0745532+00:00","Level":"Information","MessageTemplate":"Executed DbCommand ({elapsed}ms) [Parameters=[{parameters}], CommandType='{commandType}', CommandTimeout='{commandTimeout}']{newLine}{commandText}","Properties":{"elapsed":"0","parameters":"@p1='?', @p0='?'","commandType":"Text","commandTimeout":30,"newLine":"\n","commandText":"UPDATE \"HealthCheckExecutionEntries\" SET \"Duration\" = @p0\nWHERE \"Id\" = @p1;\nSELECT changes();","EventId":{"Id":20101,"Name":"Microsoft.EntityFrameworkCore.Database.Comma …

Uniform conversion for all datetime.

---

src/HealthChecks.NpgSql/DependencyInjection/NpgSqlHealthCheckBuilderExtensions.cs
src/HealthChecks.NpgSql/NpgSqlHealthCheck.cs

The NpgSql healthcheck missed the option for a ClientCertificateCallback (to connect to SSL encrypted database instances). The motivation for this PR. However, it is now also possible to set other properties within the NpgsqlConnection class (the type of the action).
**Note:** I've changed the Unit test for the NpgSql project locally to test my certificate on my database instance and it passed the test.

Added an optional action for Npgsql-specific configurations

---

src/HealthChecks.UI.Client/UIResponseWriter.cs

This will allow users to customize the way their health check responses are serialized. For example, to use something other than camel case:
```csharp
app.UseHealthChecks("/healthz", new HealthCheckOptions
{
Predicate = _ => true,
ResponseWriter = (context, report) => UIResponseWriter.WriteHealthCheckUIResponse(context, report, settings =>
{
settings.ContractResolver = new DefaultContractResolver();
})
});
```
It maintains full backwards compatibility with the existing API.

Added overload of WriteHealthCheckUIResponse that allows for custom JSON serialization settings

---

src/HealthChecks.SqlServer/DependencyInjection/SqlServerHealthCheckBuilderExtensions.cs
test/UnitTests/DependencyInjection/SqlServer/SqlServerUnitTests.cs

As discussed in #173 
This allows you to use `services.AddSqlServer(...` if you use dependency injection for your configuration. Sample usage:
```cs
services.AddHealthChecks()
.AddSqlServer(provider => provider.GetService<DatabaseSettings>().ConnectionString,
name: "db", tags: new string[] {"readiness"});
```
which would currently require using `services.Add(new HealthCheckRegistration(...` from Microsoft.Extensions.Diagnostics.HealthChecks:
```cs
services.AddHealthChecks()
.Add(new HealthCheckRegistration("db", provider =>
{
DatabaseSettings dbSettings = provider.GetService<DatabaseSettings>();
return new SqlServerHealthCheck(dbSettings.ConnectionString, "SELECT 1;");
}, null, new string[] { "readiness" }));
```
If this seems reasonable for SQL Server, it may make sense for most (all?) …

Register a SQL Server Health Check with a factory for the connection string

---

src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/ServiceCollectionExtensions.cs

Extend settings to allow the user configuring a custom HttpMessageHandler for registered named client that is used by the HealthCheckReportCollector, this will allow user to configure credentials, proxy credentials, client certificates and all the other stuff that is present in the the message handler.
```
var customHandler = new HttpClientHandler
{
DefaultProxyCredentials = CredentialCache.DefaultNetworkCredentials,
UseDefaultCredentials = true,
Properties =
{
["1"] ="prop1",
["2"] = "prop2"
}
};
services
.AddHealthChecksUI(setupSettings: setup => {
setup.UseHttpMessageHandler(customHandler);
});
```

[UI] Allow configuring custom HttpMessageHandler in hc collector HttpClient

---

README.md
build-docker-image.ps1
build/dependencies.props
build/docker-images/HealthChecks.UI.Image/appsettings.json
doc/k8s-ui-discovery.md
doc/ui-docker.md
doc/webhooks.md
samples/HealthChecks.UI.Sample/appsettings.json
samples/HealthChecks.UIAndApi/appsettings.json
samples/HealthChecks.UIAndApiCustomization/appsettings.json
src/HealthChecks.UI/ConfigurationExtensions.cs
src/HealthChecks.UI/Keys.cs
src/HealthChecks.UI/ServiceCollectionExtensions.cs
test/FunctionalTests/HealthChecks.UI/Configuration/appsettings.json

Fixes #216 being retro compatible.
It reads the new section (HealthChecksUI) and if not declared it fallbacks to the previous key setting.(HealthChecks-UI)
Updated all documentation containing old key HealthChecks-UI
I have built a docker image using this bytes and published it to an Azure Web App for Containers and it is now working as you can check here:
https://landechecks.azurewebsites.net/healthchecks-ui

[UI] #216 New Configuration Section Key Compatible with Azure Web Apps

---

build/docker-images/HealthChecks.UI.Image/Configuration/AzureAppConfiguration.cs
build/docker-images/HealthChecks.UI.Image/Configuration/AzureAppConfigurationKeys.cs
build/docker-images/HealthChecks.UI.Image/Configuration/Helpers/EnvironmentVariable.cs
build/docker-images/HealthChecks.UI.Image/Extensions/IConfigurationBuilderExtensions.cs
build/docker-images/HealthChecks.UI.Image/HealthChecks.UI.Image.csproj
build/docker-images/HealthChecks.UI.Image/Program.cs
doc/ui-docker.md

Adds feature #213 
Configuring health checks using Enviroment Variables with current docker image is a little bit tricky. We should give the chance to the users to use Azure App Configuration to setup their healthchecks, webhooks and other settings in Azure

[UI Docker image] Configurable Azure app configuration service #213

---

build/dependencies.props
src/HealthChecks.Elasticsearch/ElasticsearchHealthCheck.cs
src/HealthChecks.Elasticsearch/ElasticsearchOptions.cs

Hi,
This update is to allow Elastic Search Health Checks to support a server certificate validation callback. The elastic search IConnectionSettingValues supports this.
Thanks
Trent

Elastic Search Health Checks - Support for Certificate Validation

---

AspNetCore.Diagnostics.HealthChecks.sln
README.md
build.ps1
build/dependencies.props
src/HealthChecks.Publisher.Datadog/DatadogPublisher.cs
src/HealthChecks.Publisher.Datadog/DependencyInjection/DatadogHealthCheckBuilderExtensions.cs
src/HealthChecks.Publisher.Datadog/HealthChecks.Publisher.Datadog.csproj

Implementing #239: Creating a new Datadog publisher package.
The new package uses the official Datadog DogStatsD library: https://github.com/DataDog/dogstatsd-csharp-client.
The recommended Datadog strategy is to send custom metrics to the agent and let the agent handle communication with Datadog APIs.
The assumption here is that the datadog agent is running locally, either as a process or a sidecar container. If that's not the case, agent server name is configurable.

Datadog Publisher

---

doc/k8s-ui-discovery.md
src/HealthChecks.UI/Core/Discovery/K8S/KubernetesResponses.cs
test/UnitTests/UI/Kubernetes/Discovery/KubernetesAddressFactoryTests.cs
test/UnitTests/UI/Kubernetes/SampleData/local-cluster-discovery-sample.json
test/UnitTests/UI/Kubernetes/SampleData/remote-cluster-discovery-sample.json

When the targetPort of a Kubernetes service is named instead of a static int, this error occurs:
```
Newtonsoft.Json.JsonReaderException : Could not convert string to integer: ui. Path 'items[4].spec.ports[0].targetPort', line 180, position 30.
```
This error has prevented the Kubernetes service discovery from being used in most clusters, as many services (such as Tiller) use named target ports. The fix is simply to change the TargetPort to a string. This shouldn't cause any issues, as Newtonsoft.JSON will deserialize ints as strings, and the field isn't being used.

Fix JsonReaderException when a service has a named targetPort

---

src/HealthChecks.Redis/RedisHealthCheck.cs

This will avoid the potential thread block from the synchronous Connect & Ping.
Tools like [Ben.BlockingDetector](https://github.com/benaadams/Ben.BlockingDetector) output the following:
```
warn: Ben.Diagnostics.BlockingMonitor[6]
Blocking method has been invoked and blocked, this can lead to threadpool starvation.
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Object configuration, TextWriter log)
at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log)
at HealthChecks.Redis.RedisHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
at …
```

Redis, async all the way through

---

src/HealthChecks.MongoDb/MongoDbHealthCheck.cs

On` AddMongoDb` if the connection string is in the following format:
```json
mongodb://{UserName}:{Password}@{ServerName}:{ServerPort}/{DatabaseName}?readPreference=primary
```
using the extention passing only  the connection string (like the other providers)
```csharp
services.AddHealthChecks()
.AddMongoDb(Configuration["mongoDbConnectionString"] )
.AddSqlServer(Configuration["DbConnectionString"])
.AddAzureBlobStorage(Configuration["StorageConnectionStringName"])
.AddAzureServiceBusQueue(Configuration["BusConnectionString"],
Configuration["QueueName"]);
```
cause an unhealthy status, because the databaseName is null  so it's try to read all the databases  and the user dosn't have the privilegis:
```json
{"status":"Unhealthy","totalDuration":"00:00:01.3118507","entries":{"mongodb":{"data" …
```

Get Database Name from  connection string url

---

build/dependencies.props
src/HealthChecks.RabbitMQ/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs
src/HealthChecks.RabbitMQ/README.md
src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs
test/UnitTests/DependencyInjection/RabbitMQ/RabbitMQUnitTests.cs

* Addresses https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/304
* Add many configuration options that support ability to re-use a single
connection with multiple multiplexed channels.
* Add documentation around this health check to help others follow
RabbitMQ best practices

Add ability to re-use single RabbitMQ Connection

---

src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs
src/HealthChecks.Publisher.ApplicationInsights/DependencyInjection/ApplicationInsightsHealthCheckBuilderExtensions.cs
test/UnitTests/DependencyInjection/Publisher.ApplicationInsights/Publisher.ApplicationInsightsUnitTests.cs
test/UnitTests/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisherTests.cs
test/UnitTests/UnitTests.csproj

This PR implements exception tracking on App Insights as described in #299. 
My initial reaction was to add this only in the detailed report, but then I realized that I wanted to have the exceptions tracked, regardless of whether it's a detailed or summarized report.
While working on this I also found that it could be possible to refactor the code to be more DRY (e.g. creating the properties dictionary could be extracted to a method), and also that by using a mock `TelemetryChannel` tests could be added for this publisher. I didn't include those changes because I think they're out of the scope of this PR description.

Track exceptions in Application Insights publisher

---

build/dependencies.props
build/docker-images/HealthChecks.UI.Image/Configuration/UIKeys.cs
build/docker-images/HealthChecks.UI.Image/Extensions/IEndpointRouteBuilderExtensions.cs
build/docker-images/HealthChecks.UI.Image/Extensions/OptionsExtensions.cs
build/docker-images/HealthChecks.UI.Image/Startup.cs
doc/ui-docker.md

With version 3.0.3 the UI can be configured to use a custom css stylesheet for branding using a volume and an environment variable and it can also receive different env vars to configure ui, api an resources paths

[Docker Image] Custom branding stylesheet and Paths environment variables

---

src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs

Addresses #324 
This change will use the IConnectionFactory as configured or the generated ConfigurationFactory with specified SslOption set when creating a connection.

[RabbitMQ] Using SslOptions if passed in

---

build/dependencies.props
samples/HealthChecks.UI.Branding/HealthChecks.UI.Branding.csproj
samples/HealthChecks.UI.Branding/IServiceCollectionExtensions.cs
samples/HealthChecks.UI.Branding/Startup.cs
src/HealthChecks.UI/Core/UIEndpointsResourceMapper.cs
src/HealthChecks.UI/EndpointRouteBuilderExtensions.cs
src/HealthChecks.UI/HealthChecksUIConventionBuilder.cs

Fixes #305 
Right now, the composite IEndpointConventionBuilder returned in MapHealthChecksUI was only adding configured metadata to Api and Webhook endpoints.
With this PR, all assembly embedded resources as html, css, js and custom stylesheets will be protected as well.

[UI] Protect all assembly resources endpoints and add Authn and Authz demo

---

src/HealthChecks.UI/Configuration/Options.cs
src/HealthChecks.UI/Core/Extensions/UIResourceExtensions.cs
src/HealthChecks.UI/Keys.cs
src/HealthChecks.UI/assets/index.html
src/HealthChecks.UI/client/App.tsx
src/HealthChecks.UI/client/index.tsx

We use HealthChecksUI as a monitor (big screen in OPS) for our different environments (DEV, INT, STAGE, PROD). The left hand menu uses up a lot of space and could be closed initially. 
Would that be a big issue for you? 
Thanks! 
Best regards, David

AsideMenuOpened feature

---

build/dependencies.props
src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs
src/HealthChecks.Publisher.ApplicationInsights/DependencyInjection/ApplicationInsightsHealthCheckBuilderExtensions.cs
test/UnitTests/DependencyInjection/Publisher.ApplicationInsights/Publisher.ApplicationInsightsUnitTests.cs

Fixes #348 
Application Insights publisher no longer relies in static **TelemetryConfiguration.Active**
The TelemetryKey should be configured using the healthcheck parameter:
```csharp
services
.AddHealthChecks()
.AddApplicationInsightsPublisher("telemetrykey");
```
Or by using
```csharp
services.AddApplicationInsightsTelemetry()
```
that uses IConfiguration ApplicationInsights section.
https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/205bcd90fa70b5afc3f8dd967035bac7b06c00ef/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L163

Fix deprecated TelemetryConfiguration.Active in App Insights Publisher

---

src/HealthChecks.AzureKeyVault/AzureKeyVaultHealthCheck.cs
src/HealthChecks.AzureKeyVault/AzureKeyVaultOptions.cs
test/UnitTests/DependencyInjection/AzureKeyVault/AzureKeyVaultUnitTests.cs

Hi, this a proposed PR to slightly extend the already existing `HealthChecks.AzureKeyVault` created with PR #19 .
The idea is to support the check also for the cryptographic keys that can be stored in KeyVault. I noticed that another user suggested the change in the above PR, but I couldn't find any ongoing work.
Usage:
Default usage with Managed Service Identity:
```csharp
services.AddHealthChecks()
.AddAzureKeyVault(setup =>
{
setup
.UseKeyVaultUrl("https://[vaultname].vault.azure.net/")                  
.AddKey("keyname");
});
```
Usage usage client id and client secret:
```csharp
services.AddHealthChecks()
.AddAzureKeyVault(setup =>
{
setup
.UseKeyVaultUrl("https://[vaultname].vault.azure.net/")    
.UseClientSecrets("clientid", "clientsecret")
.AddKey("keyname");
});
```
Thanks.

Add Azure KeyVault cryptographic keys check

---

build/dependencies.props
src/HealthChecks.AzureKeyVault/AzureKeyVaultHealthCheck.cs
src/HealthChecks.AzureKeyVault/AzureKeyVaultOptions.cs

This PR adds the ability to configure azure key vault certificates with an optional "checkExpired" parameter that will throw an expection when the remote certificate has expired.
Sample:
```csharp
services
.AddHealthChecks()
.AddAzureKeyVault(setup =>
{
setup
.UseKeyVaultUrl("https://landevault.vault.azure.net")
.AddSecret("cosmos-key")
.AddKey("Key1")
.AddCertificate("landecert")
.AddCertificate("Cert2", checkExpired: true)
.UseClientSecrets("client", "secret");
}
```

[Azure key vault] Add certificates with configurable expiry check

---

README.md
build/dependencies.props
src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/ServiceCollectionExtensions.cs
test/FunctionalTests/HealthChecks.UI/Configuration/UIConfigurationTests.cs

Currently, the UI allows using custom HttpMessageHandlers for the Api and Webhooks endpoints but you can't configure the internal HttpClients because they are not exposed.
With this PR, the AddHealthChecksUI setup exposes new methods to configure the Http Clients as well, so you cant configure all Httpclient related stuff as Authentication headers
```csharp
services.AddHealthChecksUI(setupSettings: setup =>
{
setup.ConfigureApiEndpointHttpclient((sp, client) =>
{
//Configure api http client
})
.UseApiEndpointHttpMessageHandler(sp =>
{
return new HttpClientHandler
{
Proxy = new WebProxy("http://proxy:8080")
};
})
.ConfigureWebhooksEndpointHttpclient((sp, client) =>
{
//Configure authentication header for a remote webhook endpoint
client.DefaultRequestHeaders.Authorization = new …
```

[UI] Expose setup actions to configure Api and Webhooks http clients 

---

build/dependencies.props
src/HealthChecks.UI/Core/Extensions/UriExtensions.cs
src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs
src/HealthChecks.UI/Core/Notifications/WebHookFailureNotifier.cs
test/FunctionalTests/HealthChecks.UI/ServerAddressesServiceTests.cs

Fix https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/38#issuecomment-567552933
Uri.TryCreate reports /path as relative in Unix and macOS (file paths)
This Pull Request follows the instructions from Microsoft from this issue:
dotnet/corefx#22098
dotnet/corefx#22098 (comment)

Fix absolute unix paths with Uri.TryCreate

---

build/dependencies.props
src/HealthChecks.UI.Client/UIResponseWriter.cs

- Async json serialization to prevent thread blocking in UI Client.
- Use asp.net core 3.0 http context pipeline body writer with ` ReadOnlyMemory<byte>` implicit operator
- Reduced string allocations in empty response string and sync json serialization

[UI Client] Async serialization, http context writer pipeline usage and reduced allocations

---

src/HealthChecks.UI.Client/UIResponseWriter.cs
test/FunctionalTests/HealthChecks.Uris/UriHealthCheckTests.cs

Relates to #385 
@CarlosLanderas It seems to me that it will be much better and the advantage in comparison with the old sync version will increase more.

heap allocation optimization for JsonSerializerOptions

---

src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollectorHostedService.cs

My attempt at fixing #376.
Swallows the TaskCanceledException thrown when stopping.

Handle TaskCanceledException when halting

---

build/docker-images/HealthChecks.UI.Image/Configuration/UIKeys.cs
build/docker-images/HealthChecks.UI.Image/Extensions/OptionsExtensions.cs

Added **ui_no_relative_paths** environment variable to disable Api, Webhooks and Resources relatives paths to be able to configure absolute paths when using a reverse proxy.

[Docker image] Allow disabling relative paths for resources

---

README.md
doc/webhooks.md
samples/HealthChecks.UI.Branding/Startup.cs
src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/Core/Notifications/WebHookFailureNotifier.cs

Issue #415 
**What this PR does / why we need it**:  
Several users reported the need of configuring the message that is sent to Microsoft Teams, Slack or any other webhook target.
With this PR,  3 new functions are added to Webhook endpoint configuration.
**ShouldNotify**, receives the UI Report and returns a boolean to let the notifier know if the webhook should be invoked (Useful to configure working hours for example)
**CustomMessageFunc**: Configure the output of [[FAILURE]] bookmark
**CustomDescriptionFunc**: Configure the output of [[DESCRIPTION]] bookmark
Sample:
```csharp
setup
.AddWebhookNotification("webhook1",
uri: "status/200?code=ax3rt56s", payload: "{ message: \"Webhook report for [[LIVENESS]]: [[FAILURE]] - Description: [[DESCRIPTIONS]]\"}",
restorePayload: "{ message: …
```

Custom webhooks notification, failure and description user functions #415

---

build/dependencies.props
src/HealthChecks.Elasticsearch/DependencyInjection/ElasticsearchHealthCheckBuilderExtensions.cs
src/HealthChecks.Elasticsearch/ElasticsearchHealthCheck.cs
src/HealthChecks.Elasticsearch/ElasticsearchOptions.cs
test/UnitTests/ElasticSearchUnitTests.cs
test/UnitTests/UnitTests.csproj

Allow configuring ElasticSearch client timeout. 
We can use setup.RequestTimeout to configure the request timeout timespan:
```csharp
services.AddHealthChecks().AddElasticsearch(setup =>
{
setup.RequestTimeout = new TimeSpan(0, 0, 6);
});
```
If no setup.RequestTimeout is configured but the user configured the global healthcheck timeout, we pass this value to the RequestTimeout so the connection times out when the healthcheck does.
```csharp
services.AddHealthChecks().AddElasticsearch(setup =>
{
}, timeout: new TimeSpan(0,0,7));
```
If no option is configured, the HealthCheck will stay with it's current behaviour. No client request timeout would be configured.
**Which issue(s) this PR fixes**: #317
Please make sure you've completed the relevant …

Allow configuring Elastic Search Request Timeout #317

---

src/HealthChecks.Publisher.ApplicationInsights/ApplicationInsightsPublisher.cs

As discused in #426 this PR changes HealthChecks.Publisher.ApplicationInsights to use the active TelemetryConfiguration instead of just the active instrumentation key. This change means that ITelemetryInitializers (and other changes to the active configuration) that are add are used for AI events as well.
#426 
Yes, if for some reason a user don't want the extra configurations they have done for AI then they would now need to manually supply the instrumentation key.

Publisher ApplicationInsights to use active TmetryConfiguration

---

src/HealthChecks.EventStore/EventStoreHealthCheck.cs
test/FunctionalTests/HealthChecks.EventStore/EventStoreHealthCheckTests.cs

When attempting to health check a working EventStore connection, I was always getting an `Unhealthy` response.
After debugging, I discovered that there is an assumption in the code that the connection string must be a URI. This is not always the case, and the connection string I was using was similar to the following one taken from the EventStore documentation:
```csharp
var connectionString = "ConnectTo=tcp://admin:changeit@localhost:1113; HeartBeatTimeout=500";
```
I have added support for connection strings in the format shown above.
Please make sure you've …

Add support for non-URI EventStore connection strings.

---

src/HealthChecks.Consul/DependencyInjection/ConsulHealthCheckBuilderExtensions.cs

Small change that will allow consul settings to be changed during runtime. Pretty similar to what happens in NpgSqlHealthCheckBuilderExtensions.AddNpgSql().

Update ConsulHealthCheckBuilderExtensions.cs to allow runtime changes

---

src/HealthChecks.Aws.S3/S3HealthCheck.cs

A change to allow S3HealthCheck to use default credentials when no keys provided.

S3 to use default credentials when no keys

---

build/dependencies.props

After listening to one of our users we have considered downgrade packages from netstandard2.1 to netstandard 2.0 to increase compatibility surface as we are not using any of the added features included and we do not want to force users to upgrade their solutions.
Although all our healthchecks are already published in version 2.X.X in nuget, people might need the new storage providers that were published under version 2.1
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/468#issuecomment-615240412
Thanks to @vip32 for opening our eyes from a user perspective.

Target packages back netstandard2.0 for greater compatibility

---

build/dependencies.props
deploy/operator/crd/healthcheck-crd.yaml
src/HealthChecks.UI.K8s.Operator/Crd/HealthCheckResourceSpec.cs
src/HealthChecks.UI.K8s.Operator/Crd/NameValueObject.cs
src/HealthChecks.UI.K8s.Operator/Handlers/DeploymentHandler.cs
src/HealthChecks.UI.K8s.Operator/Handlers/ServiceHandler.cs

Allow the users to deploy healthchecks CRD with custom annotations for target service and deployment.
One clear use case is being able to configure an internal load balancer in Azure Kubernetes Service.
```yaml
apiVersion: "aspnetcore.ui/v1"
kind: HealthCheck
metadata:
name: healthchecks-ui
namespace: lande
spec:
name: ui-1
servicesLabel: HealthChecks
serviceType: LoadBalancer
serviceAnnotations:
- name: service.beta.kubernetes.io/azure-load-balancer-internal
value: "true"
deploymentAnnotations:
- name: ServiceType
value: AksInternalBalancer
```
Please reference the issue this PR will close: #489

[K8s Operator] Add service and deployment annotations to custom resource definition

---

build/dependencies.props
deploy/operator/crd/healthcheck-crd.yaml
src/HealthChecks.UI.K8s.Operator/Controller/HealthChecksController.cs
src/HealthChecks.UI.K8s.Operator/Crd/HealthCheckResourceSpec.cs
src/HealthChecks.UI.K8s.Operator/Extensions/HealthCheckResourceExtensions.cs
src/HealthChecks.UI.K8s.Operator/Extensions/IKubernetesExtensions.cs
src/HealthChecks.UI.K8s.Operator/Extensions/StringExtensions.cs
src/HealthChecks.UI.K8s.Operator/Handlers/ConfigMapHandler.cs
src/HealthChecks.UI.K8s.Operator/Handlers/DeploymentHandler.cs
src/HealthChecks.UI.K8s.Operator/Handlers/SecretHandler.cs
src/HealthChecks.UI.K8s.Operator/Operator/KubernetesAddressFactory.cs
src/HealthChecks.UI.K8s.Operator/Program.cs

This PR extends the HealthChecks UI CRD and Operator to allow the user configure branding in a very simple way.
The user just needs to configure `stylesheetPath` and `styleSheetContent` with  custom css in the yaml definition and the operator will configure all the UI docker image necessary environment variables and create a new `ConfigMap` with the css content stored as binary data.  This ConfigMap will be configured as a volume source so the UI application can read it's contents and server the stylesheet to the frontend.
```yaml
apiVersion: "aspnetcore.ui/v1"
kind: HealthCheck
metadata:
name: healthchecks-ui
namespace: lande
spec:
name: healthchecks-ui
servicesLabel: HealthChecks
serviceType: LoadBalancer
stylesheetPath: css/dotnet …
```

[K8s Operator] UI Deployment branding with extended CRD 

---

build/dependencies.props
doc/ui-changelog.md
src/HealthChecks.UI/Core/Notifications/WebHookFailureNotifier.cs

When failure descriptions bookmark is not configured by using custom functions in
`AddWebhookNotification` method, it produces a failed healthchecks error list payload that is not very comprehensive without knowing the associated services when it would be more interesting to list the liveness that are failing as default behaviour. Something like:
**identity-server, oracle and sqlserver healthchecks are failing.**

Change default webhook message to display failing liveness names

---

src/HealthChecks.UI.K8s.Operator/Operator/HealthChecksOperator.cs
src/HealthChecks.UI.K8s.Operator/Operator/HealthChecksPushService.cs

When you deploy the k8s operator using the installer tool (or manually), right now there is a race condition where the UI is being provisioned and the service watcher started. It can happen (if the cluster needs to pull the UI image for example), that the UI endpoint is not available yet and the service watcher pushes discovered services with failure result (service is ready but the pod is being provisioned). The user can re-label services and these will be automatically added but this is non desired extra-work.
With this PR, we wait for an available replica (5 secs x 10 retries max) and once the replica is up and running we start the service watcher.
The channel event is now run inside a task, so all the incoming events can run in parallel and be …

[K8s operator] Wait for available replica before watching services

---

build/dependencies.props
samples/HealthChecks.Sample/HealthChecks.Sample.csproj
samples/HealthChecks.Sample/Startup.cs
src/HealthChecks.Prometheus.Metrics/LivenessPrometheusMetrics.cs
src/HealthChecks.Prometheus.Metrics/PrometheusResponseWriter.cs
src/HealthChecks.Publisher.Prometheus/LivenessPrometheusMetrics.cs
src/HealthChecks.Publisher.Prometheus/PrometheusGatewayPublisher.cs
src/HealthChecks.Publisher.Prometheus/PrometheusResponseWriter.cs

Upgrades the Prometheus integration to use v3 of the `prometheus-net` library.
This is the smallest amount of code needed to change in order to upgrade prometheus-net and keep everything in its current state. 
To test it, I enabled the Prometheus metric endpoint in the `HealthChecks.Sample` project.
There's a bit of weirdness in this project's integration into Prometheus - Instead of having its own separate endpoint that updates the metrics and returns them in Prometheus format, it should instead rely on the standard `/metrics` Prometheus endpoint exposed by `endpoints.MapMetrics()` from `prometheus-net.AspNetCore`, and integrate into Prometheus by using `Registry.AddBeforeCollectCallback` (so that Prometheus calls this library to update the …

Upgrade prometheus-net to v3.x

---

AspNetCore.Diagnostics.HealthChecks.sln
README.md
build.ps1
build/dependencies.props
docker-compose.yml
src/HealthChecks.ArangoDb/ArangoDbHealthCheck.cs
src/HealthChecks.ArangoDb/ArangoDbOptions.cs
src/HealthChecks.ArangoDb/DependencyInjection/ArangoDbHealthCheckBuilderExtensions.cs
src/HealthChecks.ArangoDb/HealthChecks.ArangoDb.csproj
test/FunctionalTests/FunctionalTests.csproj
test/FunctionalTests/HealthChecks.ArangoDb/ArangoDbHealthCheckTests.cs
test/UnitTests/DependencyInjection/ArangoDb/ArangoDbUnitTests.cs
test/UnitTests/UnitTests.csproj

This PR add health check for [ArangoDB](https://www.arangodb.com/)
It is new project and implementation.
Please reference the issue this PR will close: #479 
ArangoDB recommend 3 .net clients:
[[1]](https://github.com/ra0o0f/arangoclient.net/) , last commit 2 years ago
[[2]](https://github.com/yojimbo87/ArangoDB-NET) , last commit 3 years ago
[[3]](https://github.com/Actify-Inc/arangodb-net-standard) , last commit 2 months ago
[link](https://www.arangodb.com/arangodb-drivers/) 
Yes. New extension mentod for `IHealthChecksBuilder` and create new nuget package.
Please make sure you've completed the relevant tasks for this PR, out of …

Add ArangoDB health check

---

build/dependencies.props

Eliminates the warnings during creating the nuget packages
Please reference the issue this PR will close: #505 

Get rid of pack warnings

---

build/dependencies.props
src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/Extensions/ServiceCollectionExtensions.cs
test/FunctionalTests/Base/TestCollectorInterceptor.cs
test/FunctionalTests/FunctionalTests.csproj
test/FunctionalTests/HealthChecks.UI/Configuration/UIHttpMessageHandlerTests.cs
test/FunctionalTests/HealthChecks.UI/DatabaseProviders/HostBuilderHelper.cs

Add support to register custom Http Delegating handlers into the handlers chain to mutate requests.
**Which issue(s) this PR fixes**: #536
Sample:
```csharp
services
.AddRouting() 
.AddTransient(sp => new CustomDelegatingHandler(tracer))
.AddTransient(sp => new CustomDelegatingHandler2(tracer))
.AddHealthChecksUI(setup =>
{
setup.AddHealthCheckEndpoint("endpoint1", "http://healthcheckurl");
setup.UseApiEndpointDelegatingHandler<CustomDelegatingHandler>();
setup.UseApiEndpointDelegatingHandler<CustomDelegatingHandler2>();
})
.AddInMemoryStorage();
```

[UI] Add support for custom Api HttpClient Delegating Handlers

---

build/dependencies.props

**What this PR does / why we need it**:  After some preview versions, we are bumping UI 3.1.1 and all storage providers to final.

Upgrade UI 3.1.1 preview and providers to final version

---

samples/HealthChecks.UIAndApiCustomization/Options/RemoteOptions.cs
samples/HealthChecks.UIAndApiCustomization/Startup.cs
samples/HealthChecks.UIAndApiCustomization/appsettings.json
src/HealthChecks.Uris/DependencyInjection/UrisHealthCheckBuilderExtensions.cs
test/UnitTests/DependencyInjection/Uri/UriUnitTests.cs

In some cases, the `Uri` for a `UriHealthCheck` is available from configuration through an `IOptions<...>` instance. It should be possible to use this `IOptions<...>` instance by retrieving it from the `IServiceProvider` instead of pulling the `Uri` directly from config yourself.
No issue was reported.
No, just an additional `UriHealthCheck` registration possibility.

Adds an AddUrlGroup extension method where Uri is provided by IServiceProvider

---

README.md

Incorrect reference to AddSqlServerStorage

---

src/HealthChecks.MongoDb/MongoDbHealthCheck.cs

This PR fixes a memory leak that happens when you get a disposable cursor from MongoDb and don't dispose it.
Also I changed methods to return only names because if you can get the names then you can get the rest, and the name string is lighter than the whole BsonDocument with bunch of other details

Fix memory leak, dispose MongoDb cursor

---

src/HealthChecks.RabbitMQ/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs
src/HealthChecks.RabbitMQ/README.md
test/FunctionalTests/FunctionalTests.csproj
test/FunctionalTests/HealthChecks.RabbitMQ/RabbitMQHealthCheckTests.cs

**Current problem**
Using this library via IConnectionFactory leads to new connections everytime the healthcheck url is called.
**Why register via IConnectionFactory?**
Because registering via IConnection leads to startup exception when rabbitMQ is not ready yet. Registering via IConnectionFactory solves this problem.
Timeline when registering via IConnection
-------- Start website> ----CRASH in DI container->----------------
---------------------------------------------------------Start RabbitMQ
Timeline when registering via IConnectionFactory
-------- Start website ---->HealthCheck 503_---->DoOtherStuff-------->HealthCheck 200----
-------------------------------------------------------Start RabbitMQ------------------------------
**Which issue(s) …

#552 RabbitMQ Use single connection when making use of IConnectionFactory

---

src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs
src/HealthChecks.CosmosDb/DependencyInjection/CosmosDbHealthCheckBuilderExtensions.cs

This adds support to health check for the CosmosDB database, if specified on the health check configuration.
#558: Add support in the CosmosDB health check to check database / collection is present 
I didn't encounter any functional tests for the CosmosDB health check. I see that for the other functional tests docker containers are being used, however, [the emulator is not yet available in Linux](https://feedback.azure.com/forums/263030/suggestions/18533509), and hence Docker. I've created a console app to test it (see [my other branch](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/compare/master...tiesmaster:558/add-health-checking-of-cosmosdb-database-with-temp- …

Add support to specify the database to check for existence

---

build/dependencies.props
src/HealthChecks.Network/DnsResolveHealthCheck.cs
src/HealthChecks.Network/Extensions/TaskExtensions.cs
src/HealthChecks.Network/FtpHealthCheck.cs
src/HealthChecks.Network/ImapHealthCheck.cs
src/HealthChecks.Network/PingHealthCheck.cs
src/HealthChecks.Network/SftpHealthCheck.cs
src/HealthChecks.Network/SmtpHealthCheck.cs
src/HealthChecks.Network/TcpHealthCheck.cs
test/FunctionalTests/HealthCheck.Network/DnsLHealthCheckTests.cs
test/FunctionalTests/HealthCheck.Network/FtpHealthCheckTests.cs
test/FunctionalTests/HealthCheck.Network/ImapHealthCheckTests.cs
test/FunctionalTests/HealthCheck.Network/PingHealthCheckTests.cs
test/FunctionalTests/HealthCheck.Network/SftpHealthCheckTests.cs
test/FunctionalTests/HealthCheck.Network/TcpHealthCheckTests.cs

**What this PR does / why we need it**: #571 
Network healthchecks don't respect timeouts configured in healthchecks registrations
**Which issue(s) this PR fixes**: #571 

[Network healthcheck] respect timeouts in underlying operations #571

---

src/HealthChecks.Kafka/KafkaHealthCheck.cs

Previously, the timeout property when used with `.AddKafka()` had no impact as the `cancellationToken` was never passed, producing the message would not time out in the specified time span.

[Kafka] Propagate Timeout to Kafka Health Check

---

deploy/operator/crd/healthcheck-crd.yaml
doc/k8s-operator.md
src/HealthChecks.UI.K8s.Operator/Constants.cs
src/HealthChecks.UI.K8s.Operator/Crd/HealthCheckResourceSpec.cs
src/HealthChecks.UI.K8s.Operator/Diagnostics/OperatorDiagnostics.cs
src/HealthChecks.UI.K8s.Operator/Extensions/ContainerExtensions.cs
src/HealthChecks.UI.K8s.Operator/Handlers/DeploymentHandler.cs
src/HealthChecks.UI.K8s.Operator/Handlers/SecretHandler.cs
src/HealthChecks.UI.K8s.Operator/Handlers/ServiceHandler.cs

**What this PR does / why we need it**: #619 
**Which issue(s) this PR fixes**: The operator CRD now exposes already UI existing settings to configure paths. The UI path was already configurable and now you can specify the UI Api Path, Resources Path, Webhooks Path and disable relative UI resources.
Please reference the issue this PR will close: #619 

[K8s operator] Expose UI paths to CRD and operator #619

---

src/HealthChecks.UI.K8s.Operator/HealthChecks.UI.K8s.Operator.csproj
src/HealthChecks.UI.K8s.Operator/Operator/HealthCheckServiceWatcher.cs
src/HealthChecks.UI.K8s.Operator/Operator/HealthChecksPushService.cs
src/HealthChecks.UI.K8s.Operator/Program.cs

It adds the Nuget Microsoft.Extensions.Http to allow the injection of the HttpClientFactory to manage the HttpClients of the HealthChecks.UI.K8s.Operator project. 
#532
No

Add HttpClientFactory in HealthChecks.UI.K8s.Operator

---

build/dependencies.props
deploy/operator/crd/healthcheck-crd.yaml
doc/k8s-operator.md
src/HealthChecks.UI.K8s.Operator/Constants.cs
src/HealthChecks.UI.K8s.Operator/Crd/HealthCheckResourceSpec.cs
src/HealthChecks.UI.K8s.Operator/Diagnostics/OperatorDiagnostics.cs
src/HealthChecks.UI.K8s.Operator/Handlers/IKubernetesClient.cs
src/HealthChecks.UI.K8s.Operator/Handlers/NotificationHandler.cs
src/HealthChecks.UI.K8s.Operator/Operator/ClusterServiceWatcher.cs
src/HealthChecks.UI.K8s.Operator/Operator/HealthChecksOperator.cs
src/HealthChecks.UI.K8s.Operator/Operator/KubernetesAddressFactory.cs
src/HealthChecks.UI.K8s.Operator/Operator/NamespacedServiceWatcher.cs
src/HealthChecks.UI.K8s.Operator/Program.cs

Add support for Cluster and Namespaced scopes.
The scope field (Cluster or Namespaced) is mandatory and will specify to the operator whether it should watch for healthchecks services in the same namespace where the UI resource is created or watch to all services in all namespaces.
If you wan't to have different UI's for different namespaced services you should use **Namespaced**
If you wan't to have a single UI that monitors all the healthchecks from the cluster you should use **Cluster**
Note: The UI resources created by the operator (deployment, service, configmap, secret, etc) will always be created in the metadata specified namespace.
```yaml
spec:
name: healthchecks-ui
scope: Namespaced #The UI will be created at specified namespace (demo) and …
```

[K8s operator] Cluster and Namespaced services support

---

src/HealthChecks.UI.InMemory.Storage/HealthChecksUIBuilderExtensions.cs
src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/Extensions/ApplicationBuilderExtensions.cs
src/HealthChecks.UI/Extensions/EndpointRouteBuilderExtensions.cs
src/HealthChecks.UI/Extensions/ServiceCollectionExtensions.cs
src/HealthChecks.UI/Keys.cs
src/HealthChecks.UI/Middleware/UIApiRequestLimitingMidleware.cs
src/HealthChecks.UI/Middleware/UISettingsMiddleware.cs
test/FunctionalTests/HealthChecks.UI/UIApiRequestLimitingTests.cs

Additional security mechanisms to avoid UI api abuse by allowing the user to configure the maximum number of active requests in the backend api. When the middleware semaphore has not available slots a 429 too many requests is returned from the server.
Added the initial ui settings middleware for the next steps, that will be removing the polling interval settings in the front-end for security.

[UI] Api request limitting middleware and initial UI settings middleware

---

src/HealthChecks.UI/Core/Extensions/UIResourceExtensions.cs

Respect the settings used on UseRelativeApiPath when retrieving ui-settings
**What this PR does / why we need it**: Previous change broke the retrival of ui-settings on hosts requiring relative pathing.
**Which issue(s) this PR fixes**: #642

Repect the settings used on UseRelativeApiPath when retrieving ui-settings

---

README.md
src/HealthChecks.Prometheus.Metrics/Extensions/ApplicationBuilderExtensions.cs
test/FunctionalTests/HealthChecks.Prometheus.Metrics/PrometheusResponseWriterTests.cs

This is needed in order to have prometheus read metrics when health check status is failing.
**Which issue(s) this PR fixes**: #566 
Please reference the issue this PR will close: #566 

Issue #566:Customize HTTP status codes for Prometheus exporter

---

src/HealthChecks.AzureStorage/AzureBlobStorageHealthCheck.cs
src/HealthChecks.AzureStorage/DependencyInjection/AzureStorageHealthCheckBuilderExtensions.cs

Azure Blob Health Checks Need Support For Custom Client Version
No existing PR.
The original is that I use AzureStorage Health Check and I got an unhealty result with "Unhealty with 'null'" message.
I clone the source code and find the blob client return Header error that I solve in my application with set the client version to earlier version.
So I need to set the version of blob client to use the health check extension.
I fix it with adding an optional parameters in AddAzureBlobStorage Function and the related configurations.
Yes.

Add Support For Azure Storage Options (Client Version)

---

src/HealthChecks.Aws.S3/DependencyInjection/S3HealthCheckBuilderExtensions.cs
src/HealthChecks.AzureKeyVault/DependencyInjection/AzureKeyVaultHealthChecksBuilderExtensions.cs
src/HealthChecks.Consul/DependencyInjection/ConsulHealthCheckBuilderExtensions.cs
src/HealthChecks.CosmosDb/DependencyInjection/CosmosDbHealthCheckBuilderExtensions.cs
src/HealthChecks.DocumentDb/DependencyInjection/DocumentDbHealthCheckBuilderExtensions.cs
src/HealthChecks.DynamoDb/DependencyInjection/DynamoDbHealthCheckBuilderExtensions.cs
src/HealthChecks.Elasticsearch/DependencyInjection/ElasticsearchHealthCheckBuilderExtensions.cs
src/HealthChecks.Gcp.CloudFirestore/DependencyInjection/CloudFirestoreHealthCheckBuilderExtensions.cs
src/HealthChecks.Gremlin/DependencyInjection/GremlinHealthCheckBuilderExtensions.cs
src/HealthChecks.Hangfire/DependencyInjection/HangfireHealthCheckBuilderExtensions.cs
src/HealthChecks.IdSvr/DependencyInjection/IdSvrHealthCheckBuilderExtensions.cs
src/HealthChecks.MySql/DependencyInjection/MySqlHealthCheckBuilderExtensions.cs
src/HealthChecks.Network/DependencyInjection/NetworkHealthCheckBuilderExtensions.cs
src/HealthChecks.NpgSql/DependencyInjection/NpgSqlHealthCheckBuilderExtensions.cs
src/HealthChecks.Oracle/DependencyInjection/OracleHealthCheckBuilderExtensions.cs
src/HealthChecks.Publisher.ApplicationInsights/DependencyInjection/ApplicationInsightsHealthCheckBuilderExtensions.cs
src/HealthChecks.RabbitMQ/DependencyInjection/RabbitMQHealthCheckBuilderExtensions.cs
src/HealthChecks.Redis/DependencyInjection/RedisHealthCheckBuilderExtensions.cs
src/HealthChecks.SignalR/DependencyInjection/SignalRHealthCheckBuilderExtensions.cs
src/HealthChecks.Solr/DependencyInjection/SolrHealthCheckBuilderExtensions.cs
src/HealthChecks.Sqlite/DependencyInjection/SqliteHealthCheckBuilderExtensions.cs
src/HealthChecks.System/DependencyInjection/SystemHealthCheckBuilderExtensions.cs
src/HealthChecks.Uris/DependencyInjection/UrisHealthCheckBuilderExtensions.cs

Removes extra ending param from .NET doc comments
Please reference the issue this PR will close: #671 
Visual Studio added some spaces on saved, also formatted some tabs vs spaces

Removes extra param from .NET doc comments

---

build/dependencies.props

This PR updates SendGrid nuget package to version 9.21.0 which added previously removed [constructor ](https://github.com/sendgrid/sendgrid-csharp/issues/1027)which in turn broke SendGrid HealthCheck
Please reference the issue this PR will close: #586 
-none
-no

Update SendGrid nuget to 9.21.0 to resolve #586

---

build/dependencies.props
src/HealthChecks.UI.K8s.Operator/Operator/ClusterServiceWatcher.cs
src/HealthChecks.Uris/DependencyInjection/UrisHealthCheckBuilderExtensions.cs
test/UnitTests/UnitTests.csproj
test/UnitTests/Uris/UrisHealthcheckTests.cs

Allow Uris HealthCheck method overloads to setup delegates to configure HttpClient and the primary Http Message handler.
Sample usage:
```csharp
services.AddSingleton(new ApiKeyConfiguration { HeaderName = "X-API-KEY", HeaderValue = "my-api-key"});
Action<IServiceProvider, HttpClient> clientConfigurationCallback = (sp, client) => {
var keyConfiguration = sp.GetRequiredService<ApiKeyConfiguration>();
client.DefaultRequestHeaders.Add(keyConfiguration.HeaderName, keyConfiguration.HeaderValue);
};
Func<IServiceProvider, HttpMessageHandler> configureHttpClientHandler = _ => new MyCustomMessageHandler();
services
.AddHealthChecks()
.AddUrlGroup(new Uri(RequestUri), HttpMethod.Post, hcname, 
configureClient: clientConfigurationCallback, configureHttpMessageHandler: configureHttpClientHandler); …
```

Allow Uris healthcheck to configure HttpClient and custom HttpMessageHandler

---

src/HealthChecks.Prometheus.Metrics/Extensions/ApplicationBuilderExtensions.cs
src/HealthChecks.Prometheus.Metrics/HealthChecks.Prometheus.Metrics.csproj
src/HealthChecks.Prometheus.Metrics/LivenessPrometheusMetrics.cs
src/HealthChecks.Prometheus.Metrics/PrometheusResponseWriter.cs

Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
Users on .net core 2.2 would like HealthChecks.Publisher.Prometheus functionality
- [X ] Code compiles correctly
- [X ] Created/updated tests
- [X ] Unit tests passing
- [X ] End-to-end tests passing
- [X ] Extended the documentation
- [X ] Provided sample for the feature

backport HealthChecks.Publisher.Prometheus to .net-core-2.2

---

README.md
src/HealthChecks.Network/DependencyInjection/NetworkHealthCheckBuilderExtensions.cs
src/HealthChecks.Network/SslHealthCheck.cs
src/HealthChecks.Network/SslHealthCheckOptions.cs
test/FunctionalTests/HealthCheck.Network/SslHealthCheckTests.cs
test/UnitTests/DependencyInjection/Network/NetworkUnitTests.cs

Add new HealthCheck SSL in AspNetCore.HealthChecks.Network for check validity of certificate or the expire date.
Verify SSL connection and validate certificate:
* If is not valid return unhealthy state.
* If is about to expire return degraded state.
* You can use checkLeftDays option for many days left to expire check
- [ x] Code compiles correctly
- [ x] Created/updated tests
- [ x] Unit tests passing
- [ x] End-to-end tests passing
- [ x] Extended the documentation

Add to AspNetCore.HealthChecks.Network new SSL certificate HealthCheck

---

src/HealthChecks.RavenDB/RavenDBHealthCheck.cs
test/FunctionalTests/HealthChecks.RavenDB/RavenDBWithSingleConnectionStringHealthCheckTests.cs

- do not create DocumentStore on each healthcheck - initialization performs additional and unnecessary calls to the server causing a lot of traffic
- use more lightweight endpoints to perform the healthchecks

Optimized RavenDB HealthChecks

---

build/dependencies.props

Bumps SSH.NET to [2020.0.1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.1) to fix a build failure when publishing a self-contained app.
Error when publishing a self-contained app.
Please reference the issue this PR will close: #735 
This is the dependency graph for the version of SSH.NET that AspNetCore.HealthChecks.Network is currently using (2016.1.0):
```
AspNetCore.HealthChecks.Network 5.0.1
-> SSH.NET 2016.1.0
-> System.Net.Sockets 4.1.0
-> runtime.unix.System.Net.Sockets 4.3.0
-> System.Threading.ThreadPool (>= 4.3.0)
-> System.Threading.ThreadPool (>= 4.0.10)
```
As you can see, there's a conflict in `System.Threading.ThreadPool (>= 4.3.0)` and …

Bump SSH.NET version to 2020.0.1

---

src/HealthChecks.AzureServiceBus/AzureServiceBusHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusQueueHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusSubscriptionHealthCheck.cs
src/HealthChecks.AzureServiceBus/AzureServiceBusTopicHealthCheck.cs
src/HealthChecks.AzureServiceBus/DependencyInjection/AzureServiceBusHealthCheckBuilderExtensions.cs
test/UnitTests/DependencyInjection/AzureServiceBus/AzureServiceBusQueueUnitWithTokenUnitTests.cs
test/UnitTests/DependencyInjection/AzureServiceBus/AzureServiceBusSubscriptionWithTokenUnitTests.cs
test/UnitTests/DependencyInjection/AzureServiceBus/AzureServiceBusTopicWithTokenUnitTests.cs

Allows service bus to be setup using service authentication rather than requiring  a key
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/753
No, only additional functionality 

Allow Service bus to generate tokens from AD rather than needing a key

---

src/HealthChecks.AzureServiceBus/AzureEventHubHealthCheck.cs

What this PR does / why we need it:
It fixes the creation of an EventHubProducerClient from a EventHubConnection
Which issue(s) this PR fixes:
#779

eventhubproducerclient from eventhubconnection

---

src/HealthChecks.RabbitMQ/RabbitMQHealthCheck.cs

Allows `RabbitMQ.Client.ConnectionFactory` to infer ssl options if none supplied.
Please reference the issue this PR will close: #849 

Fix RabbitMQHealthCheck for SSL endpoints

---

src/HealthChecks.AzureServiceBus/AzureServiceBusSubscriptionHealthCheck.cs

Fix for race condition in AzureServiceBusSubscriptionHealthCheck

---

src/HealthChecks.Redis/DependencyInjection/RedisHealthCheckBuilderExtensions.cs
test/HealthChecks.Redis.Tests/DependencyInjection/RegistrationTests.cs

**What this PR does / why we need it: 
This pull request adds support for configuring the key vault URI and option using an IServiceProvider similar to how the SqlServerHealthCheck supports this for a connection string. This way the ASP.net core options pattern can be used to retrieve the key vault URI and/or keys and secrets. 
So instead of this: 
var provider = services.BuildServiceProvider(); 
var settings = services.GetRequiredService<IOptions<MyOptions>>();
services.AddHealthChecks().AddRedis( settings.Value.RedisConnectionString);
You can now do something like this:
services.AddHealthChecks().AddRedis( sp => services.GetRequiredService<IOptions<MyOptions>>().Value.RedisConnectionString); 
**Which issue(s) this PR fixes: 
none 
**Special notes for your reviewer**: 
This is based on …

Added support for using IServiceProvider when configuring Redis check

---

src/HealthChecks.AzureStorage/AzureBlobStorageHealthCheck.cs

This pull request allows for the AzureBlobHealthCheck to use Azure AD roles for authentication.
Specially it allows an user with the role `Storage Blob Data Contributor` to run the health check.
This will fix the issue #783
`Storage Blob Data Contributor` is an Azure AD RBAC role that can read and write data to storage containers. Its typically used together with Managed Identities. The `Storage Blob Data Contributor` only have a very limited set of permissions (See image)
The GetServiceProperties requires account ownership, that you generally don't wanna delegate to your account.
As a note, an Storage Account Key equals full account ownership.
**Does this PR introduce a …

Allow AzureBlobHealthCheck to work with "Storage Blob Data Contributor"

---

deploy/operator/crd/healthcheck-crd.yaml
doc/k8s-operator.md
src/HealthChecks.UI.K8s.Operator/Crd/HealthCheckResourceSpec.cs
src/HealthChecks.UI.K8s.Operator/Crd/ResourceDefinitionObjects.cs
src/HealthChecks.UI.K8s.Operator/Handlers/DeploymentHandler.cs

**What this PR does / why we need it**: Allows the specification of tolerations on the HealthCheck custom resource in order to allow tolerations to be specified on the deployment.
**Which issue(s) this PR fixes**: Issue #798
Please reference the issue this PR will close: #798
**Special notes for your reviewer**: N/A
**Does this PR introduce a user-facing change?**: No, this feature is backwards compatible

Allow the specification of tolerations on the health check custom resource definition.

---

src/HealthChecks.Uris/UriHealthCheck.cs

Change enables requests to endpoints requiring http/2.
Current behaviour is that even when using `configureClient: (provider, client) => client.DefaultRequestVersion = HttpVersion.Version20` in the `AddUrlGroup` extension, the HttpRequestMessage will be created with a default Version of HttpVersion.Version11 thereby making it functionally impossible to test an endpoint that requires http/2.
This change is functionally equivalent to how the HttpRequestMessage is handled inside the HttpClient. See: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L821
No

Added support for non-default http version and version policy

---

src/HealthChecks.AzureServiceBus/DependencyInjection/AzureServiceBusHealthCheckBuilderExtensions.cs
test/HealthChecks.AzureServiceBus.Tests/DependencyInjection/AzureEventHubRegistrationTests.cs
test/HealthChecks.AzureServiceBus.Tests/DependencyInjection/AzureServiceBusQueueRegistrationTests.cs
test/HealthChecks.AzureServiceBus.Tests/DependencyInjection/AzureServiceBusQueueUnitWithTokenRegistrationTests.cs
test/HealthChecks.AzureServiceBus.Tests/DependencyInjection/AzureServiceBusSubscriptionRegistrationTests.cs
test/HealthChecks.AzureServiceBus.Tests/DependencyInjection/AzureServiceBusSubscriptionWithTokenRegistrationTests.cs
test/HealthChecks.AzureServiceBus.Tests/DependencyInjection/AzureServiceBusTopicRegistrationTests.cs
test/HealthChecks.AzureServiceBus.Tests/DependencyInjection/AzureServiceBusTopicWithTokenRegistrationTests.cs

As done for SQL Server in #175 
This allows for you to use `services.AddAzureServiceBusTopic(...`, `services.AddAzureServiceBusQueue(...` and `services.AddAzureEventHub(...` if you use dependency injection for your configuration. 
Sample usage:
```cs
services.AddAzureServiceBusQueue(
provider => provider.GetService<SasmpleQueueConfig>().ConnStr, 
provider => provider.GetService<SampleQueueConfig>().QueueName, 
tags: new string[] { "liveness" });
```
Please let me know your thoughts on having two factories for these (one for the connection string, and one for the name). The alternative is for there to be a single factory that returns some new object with both the connection string and queue name on, but I wasn't sure what would be preferred.

Register Azure Service Bus health checks with factories

---

src/HealthChecks.Redis/HealthChecks.Redis.csproj
src/HealthChecks.Redis/RedisHealthCheck.cs

**What this PR does / why we need it**: This PR solves the reconnection problem in Redis with Sentinel arch after master node is missing
**Which issue(s) this PR fixes**: Fixes https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1003

Redis: Renew the underlying connection if there is an exception

---

.github/workflows/healthchecks_oracle_cd.yml
.github/workflows/healthchecks_oracle_cd_preview.yml
.github/workflows/healthchecks_oracle_ci.yml
test/HealthChecks.Oracle.Tests/Functional/OracleHealthCheckTests.cs
test/HealthChecks.Oracle.Tests/HealthChecks.Oracle.Tests.csproj

fixes #1019 
Changes:
- oracleinanutshell/oracle-xe-11g   ->   gvenzl/oracle-xe:18-slim for CI/CD
- xe   ->   XEPDB1
- `health-*` options for `docker create` were added for CD (skipped for CI since CI has long-running `dotnet format` before tests)

Fix oracle tests

---

README.md
src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/Extensions/ServiceCollectionExtensions.cs
test/HealthChecks.UI.Tests/Functional/Configuration/UIHttpMessageHandlerTests.cs

**What this PR does / why we need it**: 
Add support to register custom delegating handlers for webhooks HttpClient to mutate requests.
**Which issue(s) this PR fixes**: #1023 
Sample:
```
services
.AddRouting() 
.AddTransient(sp => new CustomDelegatingHandler(tracer))
.AddHealthChecksUI(setup =>
{
setup.AddHealthCheckEndpoint("endpoint1", "http://healthcheckurl");
setup.AddWebhookNotification("webhook1", "https://webhookurl", "sample payload");
setup.UseWebHooksEndpointDelegatingHandler<CustomDelegatingHandler>();
})
.AddInMemoryStorage();
```

[UI] Add support for custom webhooks HttpClient delegating handlers

---

deploy/operator/crd/healthcheck-crd-pre-v1.22.yaml
deploy/operator/crd/healthcheck-crd.yaml

When deploying the healthchecks operator on the latest version of `kind` it will fail, because `apiextensions.k8s.io/v1beta1` is not supported any longer.
This bumps the `apiVersion` to the stable version and adds minimal changes to adhere to the specification.
Fixes #723 
**Special notes for your reviewer**: -

Bumping apiVersion for healtchecks crd definition

---

src/HealthChecks.UI/client/components/LivenessDetail.tsx

Currently API is returning history in Desc Order (which is correct), but on UI we are showing older on TOP which is not really obvious.
**Does this PR introduce a user-facing change?**: YES
It will show histories, as it is shown on documentation: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#health-status-history-timeline

Most recent history should be on TOP.

---

src/HealthChecks.UI/assets/healthchecksui.css
src/HealthChecks.UI/client/components/CheckTable.tsx

This PR solves the problem with misaligned tags for some font families/sizes. Moreover, CheckTable component is refactored (favoring immutability, types over interfaces, removing unnecesary typing like FunctionComponent and improving naming)
#887 
**Does this PR introduce a user-facing change?**: Yes

fix(ui-checktable): solves problem with misaligned tags

---

src/HealthChecks.Elasticsearch/ElasticsearchHealthCheck.cs
src/HealthChecks.Elasticsearch/ElasticsearchOptions.cs

This PR adds authentication by API Key to Elastic healthcheck.
#1117 
**Special notes for your reviewer**: I did not created or updated any tests because there were not any tests for the other types of authorization for Elastic. I actually tried settings up some tests but I could not set up a docker container that had an initial API Key in Elastic Search for me to try, so I only tested manually. I also did not update the documentation and I have not provided a sample for the feature because I could not find documentation or sample of the other authentication methods
**Does this PR introduce a user-facing change?**:  I am not sure what you mean, but it …

Added elasticsearch api key authentication

---

doc/k8s-operator.md

The remainder of the demo examples use `demo` namespace, but the first command was creating some namespace called `lande`
**What this PR does / why we need it**: It simply corrects the documentation.
**Which issue(s) this PR fixes**: The first command on k8s sample was creating a different namespace
**Does this PR introduce a user-facing change?**:  NO

Documentation: Correction on initial demo namespace

---

src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollector.cs

**What this PR does / why we need it**: Add basic authentication to the httpclient request headers, from the endpoint URI (UserInfo string), in GetHealthReportAsync. Allows the UI to get reports from endpoints configured to require basic authentication, by including the basic authentication credentials in the endpoint confiuration URI (appsettings.json)
Please reference the issue this PR will close:

Support basic auth of the endpoint uri in GetHealthReportAsync

---

doc/webhooks.md
samples/HealthChecks.UI.Branding/Startup.cs
src/HealthChecks.UI/Configuration/Settings.cs
src/HealthChecks.UI/Core/Notifications/WebHookFailureNotifier.cs

**What this PR does / why we need it**: Adds the liveness name to the custom notification functions to increase customizability of notifications.
**Which issue(s) this PR fixes**:  This is a partial solution to #1114. I think that the functions can be further improved but this is a first step that will increase the ability to customise the custom notifications.
Please reference the issue this PR will close: #1114 

Add livenessName to notification callback functions

---

samples/HealthChecks.UI.Branding/Startup.cs
src/HealthChecks.Nats/DependencyInjection/NatsHealthCheckBuilderExtensions.cs
src/HealthChecks.Nats/NatsHealthCheck.cs

Fix for memory leak in NATS

---

src/HealthChecks.Publisher.Seq/SeqOptions.cs
src/HealthChecks.Publisher.Seq/SeqPublisher.cs
test/HealthChecks.Publisher.Seq.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.Publisher.Seq.Tests/Functional/SeqPublisherTests.cs
test/HealthChecks.Publisher.Seq.Tests/HealthChecks.Publisher.Seq.approved.txt

- Fixes a bug where the Seq publisher does not handle trailing slashes
- Fixed Seq publisher not respecting the cancellation token
- Throw exception on null/empty endpoint in `SeqOptions`
- `SeqOptions.ApiKey` is now nullable to handle cases where no api key is required
- Fixed `seq_publisher_registration_should.add_healthcheck_when_properly_configured` options configured incorrectly
#1171
No

Fix seq trailing slash, respect cancellation token, make SeqOptions.ApiKey nullable

---

src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs
src/HealthChecks.CosmosDb/DependencyInjection/CosmosDbHealthCheckBuilderExtensions.cs
src/HealthChecks.CosmosDb/TableServiceHealthCheck.cs
test/HealthChecks.CosmosDb.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.CosmosDb.Tests/HealthChecks.CosmosDb.approved.txt

Adds a new builder extension for registering CosmosDb/TableService health check, that accepts a `TokenCredential` for authentication using managed identities.
Currently we have to pass a connection string to the cosmos account, which includes the authorization key. This is not best practice in Azure, and managed identity use is recommended.
Please reference the issue this PR will close: #1298, #1134

Add extension for CosmosDb/TableService that accepts TokenCredential for authentication

---

build/dependencies.props
src/HealthChecks.AzureServiceBus/AzureEventHubHealthCheck.cs

** Fix leak on producer creation ** 
After some investigations, I notice that the event hub health check can leak some memory ( consistently ) due to creation of the event hub producer clients, after check the code these are transient but these also create unamanaged resources and not disposes resources produce the leak...
This bug is related with the issue https://github.com/Azure/azure-sdk-for-net/issues/30119#issuecomment-1195502902

Reduce the transient creation of the event hub producer

---

build/dependencies.props
src/HealthChecks.AzureStorage/AzureBlobStorageHealthCheck.cs
src/HealthChecks.AzureStorage/AzureFileShareHealthCheck.cs
src/HealthChecks.AzureStorage/AzureQueueStorageHealthCheck.cs
test/HealthChecks.AzureStorage.Tests/AzureBlobStorageHealthCheckTests.cs
test/HealthChecks.AzureStorage.Tests/AzureFileShareHealthCheckTests.cs
test/HealthChecks.AzureStorage.Tests/AzureQueueStorageHealthCheckTests.cs

**What this PR does / why we need it**:  In the PR https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1372, I mistakenly used `GetProperties()` on the various Azure Storage service clients to probe service health, but these require more permissions than typically is assigned to a user. Instead, each service now uses different service-specific data-plane APIs to probe health.
Please reference the issue this PR will close: Relates to https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/806

Fix (Again) Erroneous Usage of Owner Azure Storage Permissions

---

.editorconfig
.gitignore
AspNetCore.Diagnostics.HealthChecks.sln

When working on a separate PR I noted a couple of quality of life improvements on the repo:
- Do not force new line on approval test specifications. Before this change, Visual Studio would add a new line on the approval test spec file on save, which means you'd be forced to edit those files in a separate text editor.
- Add `.gitignore` to solution items, so that you can view/edit the file from Visual Studio.
- Ignore approval test autogenerated output. When the API approval tests don't pass, they create an artifact `<Assembly>.received.txt` that should be ignored to prevent accidental commit.
Trivial update, no issue created.
None.
**Does this PR introduce a user-facing …

Repo QOL updates

---

src/HealthChecks.EventStore.gRPC/DependencyInjection/EventStoreHealthCheckBuilderExtensions.cs
src/HealthChecks.EventStore/DependencyInjection/EventStoreHealthCheckBuilderExtensions.cs
src/HealthChecks.EventStore/EventStoreHealthCheck.cs
test/HealthChecks.EventStore.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.EventStore.Tests/Functional/EventStoreHealthCheckTests.cs
test/HealthChecks.EventStore.Tests/HealthChecks.EventStore.approved.txt
test/HealthChecks.EventStore.gRPC.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.EventStore.gRPC.Tests/HealthChecks.EventStore.gRPC.approved.txt

This will allow creation of connection string to change depending on configuration.
I also fixed a test that was green for the wrong reason, and added `TaskCreationOptions.RunContinuationsAsynchronously` to a `TaskCompletionSource`. Let me know if you'd like these changes removed and/or put in a different PR.
Not having access to the service provider when making a connection string.
Please reference the issue this PR will close: #1531 
No, just new overloads.

Registration methods for EventStore TCP+gRPC passing in the ServiceProvider

---

src/HealthChecks.Nats/NatsHealthCheck.cs

NATS reconnect

---

test/ApiApprovalTests.cs

The current link goes to a blank docs website.
Fixed an outdated link
No

Updated Shouldly documentation link

---

src/HealthChecks.MongoDb/MongoDbHealthCheck.cs
test/HealthChecks.MongoDb.Tests/Functional/MongoDbHealthCheckTests.cs

We are experiencing unhealthy checks if a specified mongo database has no collections yet.
```
System.InvalidOperationException: Sequence contains no elements at System.Linq.ThrowHelper.ThrowNoElementsException() at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at MongoDB.Driver.IAsyncCursorExtensions.FirstAsync[TDocument](IAsyncCursor`1 cursor, CancellationToken cancellationToken) at HealthChecks.MongoDb.MongoDbHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /_/src/HealthChecks.MongoDb/MongoDbHealthCheck.cs:line 43
```
#617
None
No
Please make sure you've completed …

MongoDB - Fix Unhealthy if no collections exists in the specified database

---

build/docker-images/HealthChecks.UI.Image/Dockerfile

The Dockerfile always installs the latest node version, failing the build using the specified Node 8 version since current versions of npm do not work with Node 8.
This changes to a npm 5.* version since these version were shipped with Node 8
Can a 6.* version be published to dockerhub?
No
Validated that the built container is working using a local docker-compose setup that also worked with the 5.0.0 tag.

Use compatible version of npm

---

build/versions.props
src/HealthChecks.EventStore.gRPC/EventStoreHealthCheck.cs

Replaced subscription to the $all stream with a simple read, which is more performant.
This PR optimizes the EventStore gRPC HealthCheck by utilizing a faster method for verifying a healthy connection.
No
Link to the issue that lead to this change: https://github.com/EventStore/EventStore-Client-Dotnet/issues/241

Optimize EventStore gRPC HealthCheck

---

doc/ui-docker.md

This PR fixes the following issues regarding docker-compose.yml

Fixes some issue with docker-compose.yml

---

src/HealthChecks.EventStore.gRPC/HealthChecks.EventStore.gRPC.csproj

Added Microsoft.Bcl.AsyncInterfaces to allow EventStore.gRPC to work on net6.0
The 7.0.0 versions of EventStore gRPC do not work on net6.0 at the moment: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1692#issuecomment-1441406963
No

Added Microsoft.Bcl.AsyncInterfaces to allow EventStore.gRPC to work on net6.0

---

src/HealthChecks.UI/Core/HostedService/IHealthCheckReportCollector.cs
src/HealthChecks.UI/Extensions/ServiceCollectionExtensions.cs
test/HealthChecks.UI.Tests/HealthChecks.UI.approved.txt
test/_SHARED/ApiApprovalTests.cs

Make IHealthCheckReportCollector public and fix approval tests for UI projects

---

.github/workflows/healthchecks_ui_ci.yml

For issue https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1712, I found that there are two ways that may work
1. Modify script in [src/HealthChecks.UI/package.json](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/package.json):
use this script
`
"build": "export NODE_OPTIONS=--openssl-legacy-provider && npm run build:dll && npm run build:prod"
`
to replace the origin one
`
"build": "npm run build:dll && npm run build:prod"
`
2. Add environment parameter in [.github/workflows/healthchecks_ui_ci.yml](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/.github/workflows/healthchecks_ui_ci.yml)
I personally prefer the second one because the first approach hides an environment parameter inside a script, …

Try fix #1712

---

.github/workflows/healthchecks_ui_ci.yml
build/docker-images/HealthChecks.UI.Image/Dockerfile
src/HealthChecks.UI/build/webpack.config.js
src/HealthChecks.UI/build/webpack.dll.js
src/HealthChecks.UI/package-lock.json
src/HealthChecks.UI/package.json
test/HealthChecks.UI.Client.Tests/HealthChecks.UI.Client.approved.txt
test/HealthChecks.UI.Core.Tests/HealthChecks.UI.Core.approved.txt
test/HealthChecks.UI.Tests/Functional/Configuration/UIConfigurationTests.cs
test/HealthChecks.UI.Tests/Functional/Configuration/UIHttpMessageHandlerTests.cs
test/HealthChecks.UI.Tests/Seedwork/ProviderTestHelper.cs
test/HealthChecks.UI.Tests/xunit.runner.json

CI tests were not running for the UI projects, this PR makes minimal changes to get the UI tests to run again.
Mentioned as a pain point in: #1714 
I've disabled one test, as I could not figure out why it was failing and guessed it was more important to have the majority of tests running than none.

Reenabling tests for the UI projects in CI

---

src/HealthChecks.Network/Core/MailConnection.cs
src/HealthChecks.Network/Core/SmtpConnection.cs
src/HealthChecks.Network/SmtpHealthCheck.cs
test/HealthChecks.Network.Tests/Functional/SmtpHealthCheckTests.cs

The cancellation token in an SMTP handshake will be passed to the initial TCP connection as well, making it respect a given timeout.
It seems like this has already been an issue for IMAP connections, as there is a [Test](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/a3c8294bd4edbd1658152971fd8aac4f12e4f01f/test/HealthChecks.Network.Tests/Functional/ImapHealthCheckTests.cs#L280) and the same [Fix](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/a3c8294bd4edbd1658152971fd8aac4f12e4f01f/src/HealthChecks.Network/ImapHealthCheck.cs#L30) for that type of checks.
#1738
**Does this PR introduce a user-facing change?**
At least I'm not aware of any.
Please make sure you've completed …

Fix SMTP health checks not respecting timeout

---

src/HealthChecks.Publisher.Seq/RawEvent.cs
src/HealthChecks.Publisher.Seq/RawEvents.cs
src/HealthChecks.Publisher.Seq/SeqOptions.cs
src/HealthChecks.Publisher.Seq/SeqPublisher.cs
test/HealthChecks.Publisher.Seq.Tests/Functional/SeqPublisherTests.cs
test/HealthChecks.Publisher.Seq.Tests/HealthChecks.Publisher.Seq.approved.txt

It adds the ability to configure an action defined in SeqOptions, which enables to add/modify the properties of RawEvents which are sent to Seq.
This feature would enable users to add contextual information to the health check logs in Seq, which could be helpful for filtering and analyzing health check data across multiple applications or environments.
HealthChecks.Publisher.Seq - Add dictionary of additional static properties to SeqPublisherOptions
#1811
It's my very first PR for this project, please let me know if I missed something important.
Yes, it adds an …

Feature - seq publisher- expose raw events to options

---

src/HealthChecks.NpgSql/DependencyInjection/NpgSqlHealthCheckBuilderExtensions.cs
src/HealthChecks.NpgSql/NpgSqlHealthCheck.cs
src/HealthChecks.NpgSql/NpgSqlHealthCheckOptions.cs
test/HealthChecks.Npgsql.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.Npgsql.Tests/HealthChecks.NpgSql.approved.txt

This PR adds DbDataSource support for postgresql to allow password rotation using UsePeriodicPasswordProvider
This PR allows the following:
```
var dataSourceBuilder = new NpgsqlDataSourceBuilder(connectionString);
dataSourceBuilder.UsePeriodicPasswordProvider(async (settings, cancellationToken) =>
{
var sqlServerTokenProvider = new DefaultAzureCredential();
var tokenAsync = await sqlServerTokenProvider.GetTokenAsync(new TokenRequestContext(scopes: new[] { "https://ossrdbms-aad.database.windows.net/.default" }), cancellationToken);
return tokenAsync.Token;
},
TimeSpan.FromMinutes(55), // Interval for refreshing the token
TimeSpan.FromSeconds(5));
var dbDataSource = dataSourceBuilder.Build();
builder.Services.AddHealthChecks()
.AddNpgSql(e => dbDataSource);
```
closes #1813

PR To support DbDataSource for Postgresql

---

src/HealthChecks.Network/SftpConfiguration.cs

**Which issue(s) this PR fixes**: related to: it allows private key file authentication for sftp configuration also when keyfile has no password
Please reference the issue this PR will close: #_[1833]_
**Does this PR introduce a user-facing change?**: not really it just extends functionallity

Add overload for private key authentication on sftp configuration builder

---

src/HealthChecks.Oracle/OracleHealthCheck.cs
src/HealthChecks.Oracle/OracleHealthCheckOptions.cs
test/HealthChecks.Oracle.Tests/Functional/OracleHealthCheckTests.cs
test/HealthChecks.Oracle.Tests/HealthChecks.Oracle.approved.txt

When using pooled connections with Oracle, it is necessary to use a singleton OracleCredential.
None
It adds a new Credential property to OracleHealthCheckOptions

Support for using OracleCredential with Oracle HealthCheck

---

src/HealthChecks.Redis/DependencyInjection/RedisHealthCheckBuilderExtensions.cs
src/HealthChecks.Redis/RedisHealthCheck.cs
test/HealthChecks.Redis.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.Redis.Tests/Functional/RedisHealthCheckTests.cs
test/HealthChecks.Redis.Tests/HealthChecks.Redis.Tests.csproj
test/HealthChecks.Redis.Tests/HealthChecks.Redis.approved.txt

According to documentation Redis connection should be reused across application.
#1773 
Please reference the issue this PR will close: 
#_[1773]_
Yes.
- [ x] Code compiles correctly
- [ x] Created/updated tests
- [ x] Unit tests passing
- [ x] End-to-end tests passing

use existing connection multiplexer for redis

---

docker-compose.yml

Fix docker-compose up
Any
Any
- [V ] Code compiles correctly
- [V] Unit tests passing
- [V] End-to-end tests passing

Fixed docker compose (consul service)

---

src/HealthChecks.MySql/DependencyInjection/MySqlHealthCheckBuilderExtensions.cs
src/HealthChecks.MySql/MySqlHealthCheck.cs
src/HealthChecks.MySql/MySqlHealthCheckOptions.cs
test/HealthChecks.MySql.Tests/Functional/MySqlHealthCheckTests.cs
test/HealthChecks.MySql.Tests/HealthChecks.MySql.approved.txt

It improves MySql Health Checks by adding Query and Callback Support.
I tried to do my best mantaining original code structure.
- [V ] Code compiles correctly
- [ V] Created/updated tests
- [ V] Unit tests passing
- [ V] End-to-end tests passing
- [ V] Extended the documentation
- [V ] Provided sample for the feature

Added MySQL HealthChecks Query and Callback support.

---

src/HealthChecks.DynamoDb/DependencyInjection/DynamoDbHealthCheckBuilderExtensions.cs
src/HealthChecks.DynamoDb/DynamoDbHealthCheck.cs
src/HealthChecks.DynamoDb/DynamoDbOptions.cs
test/HealthChecks.DynamoDb.Tests/HealthChecks.DynamoDb.approved.txt

Add DynamoDBOptions.Limit and DynamoDBOptions.LastEvaluatedTableName

---

src/HealthChecks.Rabbitmq/RabbitMQHealthCheck.cs
src/HealthChecks.Rabbitmq/RabbitMQHealthCheckOptions.cs
test/HealthChecks.RabbitMQ.Tests/Functional/RabbitHealthCheckTests.cs
test/HealthChecks.RabbitMQ.Tests/HealthChecks.Rabbitmq.approved.txt

Introduce RabbitMQHealthCheckOptions.RequestedConnectionTimeout

---

src/HealthChecks.AzureKeyVault/AzureKeyVaultHealthCheck.cs
test/HealthChecks.ArangoDb.Tests/Functional/ArangoDbHealthCheckTests.cs
test/HealthChecks.AzureKeyVault.Tests/Functional/AzureKeyVaultHealthCheckTests.cs
test/HealthChecks.AzureKeyVault.Tests/HealthChecks.AzureKeyVault.Tests.csproj
test/HealthChecks.Consul.Tests/Functional/ConsulHealthCheckTests.cs
test/HealthChecks.Elasticsearch.Tests/Functional/ElasticsearchAuthenticationTests.cs
test/HealthChecks.Elasticsearch.Tests/Functional/ElasticsearchHealthCheckTests.cs
test/HealthChecks.EventStore.Tests/Functional/EventStoreHealthCheckTests.cs
test/HealthChecks.EventStore.gRPC.Tests/Functional/EventStoreHealthCheckTests.cs
test/HealthChecks.Gremlin.Tests/Functional/GremlinHealthCheckTests.cs
test/HealthChecks.Network.Tests/Functional/SslHealthCheckTests.cs
test/HealthChecks.OpenIdConnectServer.Tests/Functional/IdSvrHealthCheckTests.cs
test/HealthChecks.RabbitMQ.Tests/Functional/RabbitHealthCheckTests.cs
test/HealthChecks.RavenDb.Tests/Functional/RavenDbHealthCheckTests.cs
test/HealthChecks.RavenDb.Tests/Functional/RavenDbHealthCheckTestsSingleConnectionString.cs
test/HealthChecks.Redis.Tests/Functional/RedisHealthCheckTests.cs
test/HealthChecks.SignalR.Tests/Functional/SignalRHealthCheckTests.cs
test/HealthChecks.Solr.Tests/Functional/SolrHealthCheckTests.cs
test/HealthChecks.SqlServer.Tests/Functional/SqlServerHealthCheckTests.cs
test/HealthChecks.System.Tests/Functional/FolderHealthCheckTests.cs

Fail AzureKeyVaultHealthCheck if no keys, certificates or secrets configured

---

build/docker-images/HealthChecks.UI.Image/Program.cs
doc/ui-docker.md

By allowing the user to map a config.json file from outside the docker container into the application the user can configure the application using a json file instead of environment variables
- 'HealthChecksUI:HealthChecks:0:Name=HTTP-Api-Basic'
- 'HealthChecksUI:HealthChecks:0:Uri=http://host.docker.internal:5001/health'
He can write the classical way like in appsettings.json:
{
"HealthChecksUI": {
"HealthChecks": [
{
"Name": "HTTP-Api-Basic",
"Uri": "http://host.docker.internal:5001/health"
}
],
...
}
Note: this PR is untested, since the docker image will not compile on my maschine regarding some old node version required for this to buid.

Allow to add config.json to docker

---

src/HealthChecks.UI/HealthChecks.UI.csproj

Remove Microsoft.EntityFrameworkCore.Sqlite dependency from UI

---

build/versions.props
src/HealthChecks.UI.Client/UIResponseWriter.cs
test/HealthChecks.UI.Client.Tests/UIResponseWriterTests.cs

- By default, the serializer escapes all non-ASCII characters
- Currently non-ASCII characters are escaped, example: `你好 => \u4F60\u597D`
- This PR removes escaping for all Unicode characters
**Which issue(s) this PR fixes**: #1557
- Test added
**Does this PR introduce a user-facing change?**: No.

UIResponseWriter - Do not encode non-ASCII characters

---

build/versions.props
src/HealthChecks.DocumentDb/DocumentDbHealthCheck.cs
src/HealthChecks.DocumentDb/DocumentDbOptions.cs
test/HealthChecks.DocumentDb.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.DocumentDb.Tests/HealthChecks.DocumentDb.approved.txt

- Extends DocumentDb Health Check with option to check against provided database and collection
- When both provided then Health Check calls `ReadDocumentCollectionAsync(...)`
**Which issue(s) this PR fixes**: 
closes #333
- Registration test added
**Does this PR introduce a user-facing change?**: No.

DocumentDb - Add option to check database and collection

---

build/versions.props
src/HealthChecks.Redis/DependencyInjection/RedisHealthCheckBuilderExtensions.cs
src/HealthChecks.Redis/RedisHealthCheck.cs
test/HealthChecks.Redis.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.Redis.Tests/Functional/RedisHealthCheckTests.cs

While using `RedisHealthCheck` and reading it's code I've found two bugs.
The ctor accepts an `IConnectionMultiplexer` interface:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/c000704e1e256c932539fcd5d4c8df781e8ec1a7/src/HealthChecks.Redis/RedisHealthCheck.cs#L21
but later a cast to concrete type was being performed, which could have resulted in an exception in a scenario where the user would provide an instance of type that implements the `IConnectionMultiplexer` interface, but does not derive from `ConnectionMultiplexer` type
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/c000704e1e256c932539fcd5d4c8df781e8ec1a7/src/HealthChecks.Redis/RedisHealthCheck.cs#L31
A call to `ConnectionMultiplexer.Connect` throws when it is not possible to connect to …

RedisHealthCheck bug fixes

---

.github/workflows/healthchecks_azurekeyvault_cd.yml
.github/workflows/healthchecks_azurekeyvault_cd_preview.yml
.github/workflows/healthchecks_azurekeyvault_ci.yml
.github/workflows/healthchecks_azurekeyvault_secrets_cd.yml
.github/workflows/healthchecks_azurekeyvault_secrets_cd_preview.yml
.github/workflows/healthchecks_azurekeyvault_secrets_ci.yml
.github/workflows/reusable_cd_preview_workflow.yml
.github/workflows/reusable_cd_workflow.yml
.github/workflows/reusable_ci_workflow.yml
src/HealthChecks.Azure.KeyVault.Secrets/AzureKeyVaultSecretsHealthCheck.cs

I am about to introduce more new packages and I wonder whether it would be possible to reduce the .yml duplication by using workflows.
I wrote it based on https://dev.to/n3wt0n/avoid-duplication-github-actions-reusable-workflows-3ae8

use GH reusable workflows to reduce .yml duplication

---

build/versions.props
src/HealthChecks.Network/HealthChecks.Network.csproj

Update SSH.NET to the latest version https://www.nuget.org/packages/SSH.NET/2023.0.0
* Support for .NET 6, 7, and .NET Standard 2.0/2.1
* Support for RSA-SHA256/512 signature algorithms
* Support for parsing OpenSSH keys with ECDSA 256/384/521 and RSA
* Support for SHA256 and MD5 fingerprints for host key validation
* Added async support to SftpClient and SftpFileStream
* Added ISftpFile interface to SftpFile
* Removed support for old target frameworks
* Improved performance and stability
* Added the ability to set the last write and access time for Sftp files

Update SSH.NET to 2023.0.0

---

.github/dependabot.yml

**What this PR does / why we need it**:  The goal is to reduce the maintenance overhead, this change sets the dependabot interval to weekly updates and groups all non-major nuget changes together into a single PR (as [Github have recently released the group option](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/))
**Which issue(s) this PR fixes**:  https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2006  It doesn't fix this issue but it contributes to making versioning a little bit easier to manage.
**Special notes for your reviewer**:  None
**Does this PR introduce a user-facing change?**:  No

Updating dependabot to weekly updates and grouping non-major nuget package changes

---

AspNetCore.Diagnostics.HealthChecks.sln
src/HealthChecks.Azure.Data.Tables/DependencyInjection/AzureTablesServiceHealthChecksBuilderExtensions.cs
src/HealthChecks.Azure.Data.Tables/README.md
src/HealthChecks.Azure.KeyVault.Secrets/AzureKeyVaultSecretsHealthCheck.cs
src/HealthChecks.Azure.KeyVault.Secrets/AzureKeyVaultSecretsHealthCheckOptions.cs
src/HealthChecks.Azure.KeyVault.Secrets/DependencyInjection/AzureKeyVaultHealthChecksBuilderExtensions.cs
src/HealthChecks.Azure.KeyVault.Secrets/README.md
src/HealthChecks.Azure.Messaging.EventHubs/DependencyInjection/AzureEventHubHealthChecksBuilderExtensions.cs
src/HealthChecks.Azure.Messaging.EventHubs/README.md
src/HealthChecks.Azure.Storage.Blobs/DependencyInjection/AzureBlobStorageHealthChecksBuilderExtensions.cs
src/HealthChecks.Azure.Storage.Blobs/README.md
src/HealthChecks.Azure.Storage.Files.Shares/DependencyInjection/AzureQueueStorageHealthChecksBuilderExtensions.cs
src/HealthChecks.Azure.Storage.Files.Shares/README.md
src/HealthChecks.Azure.Storage.Queues/DependencyInjection/AzureQueueStorageHealthChecksBuilderExtensions.cs
src/HealthChecks.Azure.Storage.Queues/README.md
src/HealthChecks.CosmosDb/DependencyInjection/CosmosDbHealthCheckBuilderExtensions.cs
src/HealthChecks.CosmosDb/README.md
test/HealthChecks.Azure.Data.Tables.Tests/HealthChecks.Azure.Data.Tables.approved.txt
test/HealthChecks.Azure.Data.Tables.Tests/TableServiceHealthCheckTests.cs
test/HealthChecks.Azure.KeyVault.Secrets.Tests/HealthChecks.Azure.KeyVault.Secrets.approved.txt
test/HealthChecks.Azure.Messaging.EventHubs.Tests/HealthChecks.Azure.Messaging.EventHubs.approved.txt
test/HealthChecks.Azure.Storage.Blobs.Tests/AzureBlobStorageHealthCheckTests.cs
test/HealthChecks.Azure.Storage.Blobs.Tests/HealthChecks.Azure.Storage.Blobs.approved.txt
test/HealthChecks.Azure.Storage.Files.Shares.Tests/AzureFileShareHealthCheckTests.cs
test/HealthChecks.Azure.Storage.Files.Shares.Tests/HealthChecks.Azure.Storage.Files.Shares.approved.txt
test/HealthChecks.Azure.Storage.Queues.Tests/AzureQueueStorageHealthCheckTests.cs
test/HealthChecks.Azure.Storage.Queues.Tests/HealthChecks.Azure.Storage.Queues.approved.txt
test/HealthChecks.CosmosDb.Tests/CosmosDbHealthCheckTests.cs
test/HealthChecks.CosmosDb.Tests/HealthChecks.CosmosDb.approved.txt

Unification with existing HCs.

Editorial changes for new health checks

---

src/HealthChecks.NpgSql/DependencyInjection/NpgSqlHealthCheckBuilderExtensions.cs
src/HealthChecks.NpgSql/NpgSqlHealthCheck.cs
src/HealthChecks.NpgSql/NpgSqlHealthCheckOptions.cs
src/HealthChecks.NpgSql/README.md
test/HealthChecks.Npgsql.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.Npgsql.Tests/HealthChecks.NpgSql.approved.txt
test/HealthChecks.Npgsql.Tests/HealthChecks.Npgsql.Tests.csproj

This PR implements #2113 for Npgsql:
- offer two public `NpgSqlHealthCheckOptions` ctors: one that requires `ConnectionString` and another that requires `DataSource`. This allows us to ensure that every instance of this type is valid.
- make `ConnectionString` and `DataSource` properties readonly. This allows us to ensure that the customers are not providing both.
- add README.md and explain what we recommend and why

Improve Npgsql health check design

---

.github/workflows/healthchecks_eventstore_ci.yml
.github/workflows/healthchecks_eventstore_grpc_ci.yml

```log
[    1, 1,23:13:32.973,FTL] The option "EnableExternalTcp" is not a known option.
[    1, 1,23:13:32.974,FTL] Found unknown options. To continue anyway, set AllowUnknownOptions to true.
[    1, 1,23:13:32.974,INF] Use the --help option in the command line to see the full list of EventStoreDB configuration options.
Error: Failed to initialize container eventstore/eventstore
Error: One or more containers failed to start.
```
For more details please see https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/actions/runs/8514935948/job/23321532350?pr=2185

use lts EventStoreDB docker image as latest fails to start

---

build/docker-images/HealthChecks.UI.Image/HealthChecks.UI.Image.csproj
src/HealthChecks.AzureDigitalTwin/HealthChecks.AzureDigitalTwin.csproj
src/HealthChecks.Elasticsearch/DependencyInjection/ElasticsearchHealthCheckBuilderExtensions.cs
src/HealthChecks.Elasticsearch/ElasticsearchHealthCheck.cs
src/HealthChecks.Elasticsearch/ElasticsearchOptions.cs
src/HealthChecks.Elasticsearch/HealthChecks.Elasticsearch.csproj
src/HealthChecks.UI/build/webpack.config.js
src/HealthChecks.UI/package-lock.json
src/HealthChecks.UI/package.json
test/HealthChecks.Azure.Data.Tables.Tests/HealthChecks.Azure.Data.Tables.Tests.csproj
test/HealthChecks.Azure.KeyVault.Secrets.Tests/HealthChecks.Azure.KeyVault.Secrets.Tests.csproj
test/HealthChecks.Azure.Messaging.EventHubs.Tests/HealthChecks.Azure.Messaging.EventHubs.Tests.csproj
test/HealthChecks.Azure.Storage.Blobs.Tests/HealthChecks.Azure.Storage.Blobs.Tests.csproj
test/HealthChecks.Azure.Storage.Files.Shares.Tests/HealthChecks.Azure.Storage.Files.Shares.Tests.csproj
test/HealthChecks.Azure.Storage.Queues.Tests/HealthChecks.Azure.Storage.Queues.Tests.csproj
test/HealthChecks.AzureDigitalTwin.Tests/HealthChecks.AzureDigitalTwin.Tests.csproj
test/HealthChecks.AzureKeyVault.Tests/HealthChecks.AzureKeyVault.Tests.csproj
test/HealthChecks.AzureServiceBus.Tests/HealthChecks.AzureServiceBus.Tests.csproj
test/HealthChecks.Elasticsearch.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.Elasticsearch.Tests/Functional/ElasticsearchAuthenticationTests.cs
test/HealthChecks.Elasticsearch.Tests/HealthChecks.Elasticsearch.approved.txt

This PR will fix the #2130 . The real developer of this PR is actually #2133 but this somehow got stuck in merging. That's why I tried to get the administrative process going after almost 5 months. The credits should go to [schulz3000](https://github.com/schulz3000).
**Which issue(s) this PR fixes**: #2130
Use webpack5 syntax to include woff2 in bundle and remove url-loader that's no longer in use.
It will reinstate the icons that got lost with a previous change.

Use webpack5 syntax to include woff2 in bundle and remove url-loader

---

build/docker-images/HealthChecks.UI.Image/Dockerfile

The UI Docker won't build currently.
First, [this PR](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2194) needs to be merged since dotnet reports a vulnerability warning as error in the Azure.Identity nuget.
Then, this PR updates the runtime and sdk docker images from .NET 6 to .NET 8, because the v6 sdk won't build the project that have been upgraded to .NET 8 already.
I built the docker with these changes and it seems mostly fine safe for a few missing icons but that may be due to everything being served from localhost. Happy to contribute further.

HealthChecks.UI.Image/Dockerfile: build and run on aspnet & sdk v8

---

src/HealthChecks.MongoDb/HealthChecks.MongoDb.csproj
src/HealthChecks.UI/HealthChecks.UI.csproj

Please reference the issue this PR will close: #2265

Update MongoDB.Driver Package Version To 2.28.0

---

src/HealthChecks.MongoDb/HealthChecks.MongoDb.csproj

We can sign this assembly now because MongoDB.Driver is now signed as of v2.28.

Sign HealthChecks.MongoDb

---

src/HealthChecks.UI/assets/healthchecksui.css

Background color shouldn't be used for logo image because it conflicts with images that use transparency for example SVGs (which are the standard format for logos on the web nowadays)

Update healthchecksui.css (background color on logo element)

---

src/HealthChecks.Publisher.Datadog/DependencyInjection/DatadogHealthCheckBuilderExtensions.cs

Was not possible to customize additional parameters of the Datadog Publisher (eg. the port)
I only added an overload to expose the StatsdConfig, so, the consumers of the package can freely set any parameter supported by Datadog.

Added overload to for StatsdConfig

---

src/HealthChecks.Publisher.Datadog/DependencyInjection/DatadogHealthCheckBuilderExtensions.cs
src/HealthChecks.Publisher.Datadog/README.md
test/HealthChecks.Publisher.Datadog.Tests/DependencyInjection/RegistrationTests.cs
test/HealthChecks.Publisher.Datadog.Tests/HealthChecks.Publisher.Datadog.approved.txt

1. Ensure we resolve a singleton instance rather than create a dedicated one by default (https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2289#issuecomment-2511930940)
2. Add Readme
3. Update tests so they pass
I've removed the overload that takes a string, so it's a breaking change. It will be released as part of the 9.0 release (major version update).
cc @kevingosse

Improve Datadog health check

---

.github/workflows/healthchecks_npgsql_ci.yml
Directory.Packages.props
test/HealthChecks.Npgsql.Tests/Functional/NpgsqlHealthCheckTests.cs
test/HealthChecks.Npgsql.Tests/HealthChecks.Npgsql.Tests.csproj
test/HealthChecks.Npgsql.Tests/PostgreSQLContainerFixture.cs

Migrate HealthChecks.Npgsql tests to Testcontainers

---

.github/workflows/healthchecks_mysql_ci.yml
Directory.Packages.props
test/HealthChecks.MySql.Tests/Functional/MySqlHealthCheckTests.cs
test/HealthChecks.MySql.Tests/HealthChecks.MySql.Tests.csproj
test/HealthChecks.MySql.Tests/MySqlContainerFixture.cs

Contributes to https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2335

Migrate HealthChecks.MySql tests to Testcontainers

---

.github/workflows/healthchecks_qdrant_ci.yml
Directory.Packages.props
test/HealthChecks.Qdrant.Tests/Functional/QdrantHealthCheckTests.cs
test/HealthChecks.Qdrant.Tests/HealthChecks.Qdrant.Tests.csproj
test/HealthChecks.Qdrant.Tests/QdrantContainerFixture.cs

Contributes to https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2335

Migrate HealthChecks.Qdrant tests to Testcontainers

---

Directory.Packages.props
src/HealthChecks.SurrealDb/SurrealDbHealthCheck.cs

There is an issue with the current implementation of the `SurrealDB` healthcheck: calling `Connect` when already connected throws an exception.
Since connection and reconnection are handled internally in the library, there is no need to call the method manually. It will also be called internally within `Health` if the client is not connected.

fix: remove manual connect to SurrealDB instance on checkl
